export const en = {
  language: { label: "Language" },
  breathReveal: {
    eyebrow: "New skill: breath",
    titles: {
      fire: "{name} breathes fire!",
      storm: "{name} breathes lightning!",
      nature: "{name} lashes out thorns!",
      earth: "{name} blasts sand and rock!",
      water: "{name} breathes water!",
    },
    elements: { fire: "Fire", nature: "Nature", earth: "Earth", storm: "Storm", water: "Water" },
    howTo: "When you take the reins in a race, tap <b>{element}</b> as a rival flies right ahead or alongside: the hit slows it, knocks it back and shakes it off its line, twice as hard on the element {name}'s beats.",
    autopilot: "On Autopilot, {name} breathes by itself.",
    again: "Again!",
    done: "Got it",
  },
  infoTip: {
    label: "What is this?",
    about: "About {about}",
  },
  app: {
    back: "Back",
    saveFailed: "Your stable could not be saved on this device.",
    documentTitle: "Dragons! — {title}",
    logoLabel: "Dragons!, back to the stable",
    screensLabel: "Screens",
  },
  routes: {
    welcome: "Welcome",
    stable: "Stable",
    away: "While you were away",
    profile: "Profile",
    details: "Details",
    lineage: "Lineage",
    altar: "Soul Altar",
    race: "Race",
    races: "Race",
    results: "Results",
    ceremony: "Awards ceremony",
    more: "Settings",
    ownerProfile: "Profile",
    league: "League",
    raceEntry: "Race entry",
    exhibition: "Exhibition",
    exhibitionRace: "Exhibition race",
    editor: "Editor",
  },
  nav: { stable: "Stable", race: "Race", altar: "Altar", more: "Settings" },
  loadingScreen: { waking: "Waking the stable…" },
  genes: {
    labels: {
      body: "Torso length",
      wingspan: "Wingspan",
      neck: "Neck reach",
      tail: "Tail length",
      horns: "Headgear size",
      spines: "Crest height",
      scales: "Scale colour",
      wings: "Wing colour",
      underside: "Underside colour",
      legs: "Leg length",
      thighs: "Thigh girth",
      head: "Head",
      headgear: "Headgear",
      legShape: "Leg shape",
      wingFingers: "Wing fingers",
      feet: "Feet",
      tailTip: "Tail tip",
      hindWings: "Hind wings",
      breath: "Breath",
      eyes: "Eye colour",
      metal: "Metallic coat",
      mane: "Mane",
      markings: "Markings",
    },
    choices: {
      colours: { crimson: "Crimson", ember: "Ember", rust: "Rust", coral: "Coral", tangerine: "Tangerine", amber: "Amber", gold: "Gold", sand: "Sand", lime: "Lime", moss: "Moss", fern: "Fern", jade: "Jade", forest: "Forest", mint: "Mint", teal: "Teal", turquoise: "Turquoise", sky: "Sky", azure: "Azure", cobalt: "Cobalt", navy: "Navy", steel: "Steel", violet: "Violet", plum: "Plum", lavender: "Lavender", rose: "Rose", magenta: "Magenta", ivory: "Ivory", ash: "Ash", slate: "Slate", black: "Black", bronze: "Bronze", chocolate: "Chocolate" },
      head: { toothed: "Toothed", beaked: "Beaked", blunt: "Blunt", needle: "Needle snout", viper: "Viper" },
      headgear: { swept: "Swept horns", ram: "Ram horns", frill: "Frill", crown: "Spiked crown", antlers: "Antlers" },
      legShape: { raptor: "Raptor", feathered: "Feathered", armoured: "Armoured", spurred: "Spurred" },
      wingFingers: { claws: "Hooked claws", long: "Long fingers", stubby: "Stubby fingers", bony: "Bare bones", spikes: "Spikes" },
      feet: {
        raptor: "Raptor talons",
        eagle: "Eagle grip",
        heavy: "Heavy pads",
        webbed: "Webbed",
        sickle: "Sickle claw",
        perching: "Perching grip",
        gecko: "Gecko pads",
      },
      tailTip: { plain: "Tapered", spade: "Spade", fan: "Fan", club: "Club", stinger: "Stinger", fin: "Forked fin" },
      hindWings: { none: "None", membrane: "Hind wings", feathered: "Feathered hind wings" },
      breath: { fire: "Fire", nature: "Nature", earth: "Earth", storm: "Storm", water: "Water" },
      eyes: { gold: "Gold", amber: "Amber", jade: "Jade", ice: "Ice", blood: "Blood", violet: "Violet", moonstone: "Moonstone" },
      metal: { none: "None", gold: "Gold", silver: "Silver", goldSilver: "Gold and silver", silverGold: "Silver and gold" },
      mane: { spikes: "Spikes", element: "Element mane" },
      markings: { none: "None", leopard: "Leopard spots", zebra: "Zebra stripes", cow: "Cow patches" },
    },
  },
  riderLookFields: {
    fields: {
      build: "Build",
      ears: "Ears",
      skin: "Skin",
      eyes: "Eye colour",
      hair: "Hair",
      facialHair: "Facial hair",
      hairColor: "Hair colour",
      marks: "Marks",
      hat: "Headwear",
      goggles: "Goggles",
      scarf: "Scarf",
      gloves: "Gloves",
      boots: "Boots",
      breeches: "Breeches",
    },
    options: {
      build: { slim: "Slim", athletic: "Athletic", average: "Average", hourglass: "Hourglass", broad: "Broad", stocky: "Stocky" },
      ears: { round: "Round", pointed: "Pointed", long: "Elven" },
      skin: {
        porcelain: "Porcelain",
        rosy: "Rosy",
        fair: "Fair",
        light: "Light",
        tan: "Tan",
        golden: "Golden",
        olive: "Olive",
        bronze: "Bronze",
        brown: "Brown",
        umber: "Umber",
        deep: "Deep",
        ebony: "Ebony",
      },
      eyes: { brown: "Brown", dark: "Dark", hazel: "Hazel", amber: "Amber", green: "Green", blue: "Blue", grey: "Grey", violet: "Violet" },
      hair: {
        bald: "Bald",
        buzz: "Buzz cut",
        short: "Short",
        quiff: "Quiff",
        curly: "Curly",
        spiky: "Spiky",
        mohawk: "Mohawk",
        bob: "Bob",
        ponytail: "Ponytail",
        braid: "Braid",
        pigtails: "Pigtails",
        bun: "Bun",
        topknot: "Top knot",
        long: "Long",
        afro: "Afro",
      },
      facialHair: { none: "None", stubble: "Stubble", moustache: "Moustache", goatee: "Goatee", beard: "Beard", braided: "Braided beard" },
      hairColor: {
        black: "Black",
        espresso: "Espresso",
        brown: "Brown",
        chestnut: "Chestnut",
        auburn: "Auburn",
        ginger: "Ginger",
        strawberry: "Strawberry blond",
        blond: "Blond",
        platinum: "Platinum",
        grey: "Grey",
        white: "White",
        teal: "Teal",
        blue: "Blue",
        purple: "Purple",
        pink: "Pink",
        green: "Green",
      },
      marks: { none: "None", freckles: "Freckles", blush: "Rosy cheeks", paint: "Face paint" },
      hat: { cap: "Silks cap", aviator: "Flying cap", bandana: "Bandana", circlet: "Circlet", pointed: "Pointed hat", horned: "Horned helm", none: "None" },
      goggles: { smoke: "Smoke", amber: "Amber", emerald: "Emerald", sky: "Sky", rose: "Rose", mirror: "Gold mirror" },
      scarf: { none: "None", short: "Short", long: "Long" },
      gloves: { leather: "Leather", black: "Black", white: "White", silks: "Silks colour" },
      boots: { black: "Black", brown: "Brown", tan: "Tan", white: "White", silks: "Silks colour" },
      breeches: { white: "White", cream: "Cream", tan: "Tan", grey: "Grey", black: "Black", silks: "Silks colour" },
    },
  },
  silksFields: {
    pattern: "Pattern",
    roles: { body: "Main colour", accent: "Accent", trim: "Trim" },
    none: "None",
    patterns: {
      plain: "Plain",
      hoops: "Hoops",
      stripes: "Stripes",
      halves: "Halves",
      quarters: "Quarters",
      sash: "Sash",
      crossbelts: "Cross belts",
      chevrons: "Chevrons",
      checks: "Checks",
      diamonds: "Diamonds",
      braces: "Braces",
    },
    colors: {
      white: "White",
      cream: "Cream",
      silver: "Silver",
      grey: "Grey",
      black: "Black",
      brown: "Brown",
      maroon: "Maroon",
      scarlet: "Scarlet",
      coral: "Coral",
      orange: "Orange",
      gold: "Gold",
      yellow: "Yellow",
      lime: "Lime",
      emerald: "Emerald",
      forest: "Forest",
      mint: "Mint",
      teal: "Teal",
      sky: "Light blue",
      royal: "Royal blue",
      navy: "Navy",
      lavender: "Lavender",
      purple: "Purple",
      pink: "Pink",
    },
  },
  pickerFields: { previous: "Previous {field}", next: "Next {field}" },
  riderMaker: {
    name: "Name",
    randomName: "Another name",
    random: "Surprise me",
    groups: { body: "Body", face: "Face", hair: "Hair", accessories: "Headwear & accessories", jacket: "Jacket", kit: "Breeches, gloves & boots" },
  },
  welcomeScreen: {
    stableHand: "Stable hand",
    nameLine: "Welcome, owner! You ride every dragon you own. What should I call you?",
    nameNext: "That's me",
    meetLine: "Now, {owner}, these three kids need a home, and one of them is yours to raise. Tap one below to meet it.",
    pickLines: {
      topSpeed: "{kid} has a long, sleek body, built for the straights. Raise it, or meet another below.",
      acceleration: "{kid} has big wings and bounces back to speed in a flash. Raise it, or meet another below.",
      handling: "{kid} has a long tail and turns on a coin, built for canyons. Raise it, or meet another below.",
      weight: "{kid} is big and solid, hard to push around. Raise it, or meet another below.",
      breath: "{kid} has big headgear: a born fighter once it can breathe. Raise it, or meet another below.",
    },
    kids: "The three kids",
    allKids: "All three",
    allKidsSub: "Side by side",
    pickFirst: "Meet a kid first",
    raise: "Raise {name}",
    gift: "A gift!",
    giftLine:
      "Every new owner gets an egg too: keep it warm and it hatches a kid. When {name} is fit, enter it in the Kids League under Race. It flies on Autopilot until you take the reins, and I'll show you how in your first race.",
    giftNext: "To the stable",
  },
  ownerProfileScreen: {
    caption: "You ride every dragon you own, in these silks.",
  },
  moreScreen: {
    profile: "Profile",
    trophies: "Trophies",
    noTrophies: "Win a Gold season to take a league's trophy.",
    medals: "Medals",
    noMedals: "Finish a season on the podium of any division for a medal.",
    settings: "Look and language",
    reminders: "Reminders",
    remindersRow: "Care reminders",
    remindersOn: "On",
    remindersOff: "Off",
    remindersWhen: "Up to two a day when your dragons need care, and none between 23:00 and 06:00.",
    remindersOffText: "No reminders: check on your dragons yourself.",
    remindersAsk: "Your phone has not allowed reminders yet.",
    remindersAllow: "Allow reminders",
    remindersDenied: "Notifications from Dragons! are turned off in your phone's settings.",
    remindersOpenSettings: "Open phone settings",
    remindersWeb: "Reminders come with the iPhone and Android apps.",
    detail: "Detail",
    details: { light: "2×", full: "4×" },
    sound: "Sound",
    soundEffects: "Effects",
    soundMusic: "Music",
    developer: "Developer",
    gameClock: "Game clock",
    gameClockSpeed: "Game clock speed",
    exhibition: "Exhibition field",
    newStable: "New stable",
    confirmReset: "Really start over?",
    legal: "Legal",
    privacy: "Privacy policy",
    terms: "Terms and conditions",
  },
  parentKeys: { mutation: "Mutation", aParent: "A parent" },
  ritualTimeline: {
    raise: [
      "Stand back, owner. The old stones are waking.",
      "Hush now. The stones remember every soul that passed through them.",
      "Stand with me, owner. The circle is listening.",
    ],
    breath: ["Now, together: breathe!", "Breathe, all of you, as one!", "Give it your fire, all of you, together!"],
    success: [
      "A new soul has come through. Welcome it home, owner.",
      "There: an egg, warm from the stone. The circle has answered.",
      "Look, owner! The stones gave us a soul tonight.",
    ],
    failure: [
      "The stones keep their own counsel tonight. Let your dragons rest, and come back.",
      "No soul answered this time. It is no one's fault; the circle chooses.",
      "Only mist tonight. Rest them well; the stones will listen again.",
    ],
  },
  lineageScreen: {
    pair: "{a} × {b}",
    noLongerHere: "no longer here",
    inTheWild: "in the wild",
    inStable: "in your stable",
    childOf: "Child of {names}",
    seedBorn: "Seed-born",
    seedBornTag: "seed-born",
    gen: "Gen {gen}",
    parentLabel: "Parent {key}, {name}, open profile",
    parentGoneLabel: "Parent {key}, {name}",
    childLabel: "{name}, open profile",
    ritualOf: "A ritual of {count}",
    bodyParts: "Body parts",
    mutationTitle: { one: "A mutation!", other: "{count} mutations!" },
    mutationText: "{traits}: something no parent had.",
    partsCaption: {
      two: "Each part comes whole from one parent; now and then one mutates into something neither parent had.",
      many: "Each part comes whole from one parent; now and then one mutates into something no parent had.",
    },
    colours: "Colours",
    coloursCaption: {
      two: "Scales, wings and underside each take their colour whole from one parent, or mutate into one neither had. Shape blends between both.",
      many: "Scales, wings and underside each take their colour whole from one parent, or mutate into one no parent had. Shape blends across all {count}.",
    },
    seedBornText: "No known parents: its parts, colours and shape all came from its own seed. Its chicks will be Gen 1.",
  },
  editorScreen: {
    tabs: { dragon: "Dragon", genes: "Genes", rider: "Rider",},
    flightMode: "Flight mode",
    previous: "Previous participant",
    next: "Next participant",
    editor: "Editor",
    name: "Name",
    seed: "Seed",
    generate: "Generate",
    age: "Age",
    harness: "Harness",
    off: "Off",
    on: "On",
    harnessCaption: "The harness changes the look only; the race is the same.",
    genomeControls: "Genome controls",
    shape: "Shape",
    colours: "Colours",
    resetGenes: "Reset genes to seed",
    riderCaption: "The rider changes the look only; the race is the same.",
    reroll: "Reroll",
    pause: "Pause animation",
    play: "Play animation",
    strength: "Stars",
  },
  fieldScreen: {
    courseSeed: "Course seed",
    raceSeed: "Race seed",
    moveUp: "Move {name} up",
    moveDown: "Move {name} down",
    remove: "Remove {name}",
    race: "Race",
    course: "Course",
    age: "Age",
    caption: "Riders change the look only. The seeds and the grid fix the result.",
    theField: "The field",
    fieldCount: "{count} / {max}, P1 on pole",
    add: "Add dragon",
    shuffle: "Shuffle grid",
    start: "Start race",
    stars: "{stars}★",
  },
  dragonStatus: {
    fullyGrown: "Fully grown",
    readyToEvolve: "Ready to evolve into {age}",
    growsIn: "{age} in {time}",
    healsIn: "heals in {time}",
    tired: "Tired",
    restedIn: "rested in {time}",
    fitTired: "Fit, a little tired",
    rested: "Rested",
  },
  dragonAge: { kid: "Kid", teen: "Teen", adult: "Adult" },
  stableHome: {
    rename: "Rename",
    name: "Name",
    roster: "Roster",
    yourStable: "Your stable",
    slots: "{used} of {total}",
    wildTab: "Wild · {count}",
    egg: "Egg",
    ready: "Ready!",
    freeSlot: "Free slot",
    bookedLabel: "{name}, on the way home",
    onTheWay: "On the way",
    onTheWayHome: "On the way home · {time}",
    inTheWild: "In the wild",
    emptyWild: "No dragon is at home. Call one home from the wild.",
    emptyStable: "The stable is empty. Start a new one from More.",
    profile: "Profile",
    warm: "Warm",
    warmCount: "Warm {count}/{limit}",
    race: "Race",
    evolve: "Evolve",
    pop: "Pop!",
    crack: "Crack!",
    hatched: "Hatched!",
    grown: { teen: "Teen!", adult: "All grown up!" },
    warmGain: "An hour sooner, ⅛ ★ stronger",
  },
  yardHatch: { hatch: "Hatch", again: "Again!" },
  mood: {
    needs: {
      fullness: "Hungry!",
      happiness: "Bored…",
      cleanliness: "Needs a bath",
      exercise: "Restless",
      affection: "Feels distant",
    },
    readyToHatch: "Ready to hatch!",
    onTheWayHome: "On the way home",
    inTheWild: "In the wild",
    onAir: "On air",
    slumbering: "Slumbering · wakes in {time}",
    readyToEvolve: "Ready to evolve!",
    tired: "Tired",
    readyToRace: "Ready to race!",
  },
  needNotifications: {
    fullness: "{name} is hungry!",
    happiness: "{name} is bored…",
    cleanliness: "{name} needs a bath",
    exercise: "{name} is restless",
    affection: "{name} feels distant",
    warm: "Your egg is ready to be warmed",
    hatch: "Your egg is ready to hatch!",
    missed: "{name} misses you!",
    missedEgg: "Your egg misses you!",
    anEgg: "your egg",
    alsoOne: "{name} needs you too.",
    alsoTwo: "{a} and {b} need you too.",
    alsoMany: "{name} and {count} more need you too.",
  },
  stars: { label: "{count} of {max} stars", reach: "{count} of {max} stars, growing towards {reachable}" },
  statBars: {
    topSpeed: "Top speed",
    acceleration: "Acceleration",
    handling: "Handling",
    weight: "Weight",
    breath: "Breath",
    breathOff: "Breathes once it grows into a teen",
    hints: { topSpeed: "A long, sleek torso: fastest on a clear stretch", acceleration: "Big wings: quickly back up to speed after a hit or a bump", handling: "A long tail: tight turns without losing speed", weight: "Its bulk: wins bumps and shrugs off breath, but slower off the mark", breath: "Big headgear: harder hits that recharge sooner" },
  },
  slotMeter: { label: "Stable", slots: "{used} of {total} slots" },
  coachMarks: { next: "Next", skip: "Skip", keepWatching: "Keep watching" },
  stableTour: {
    careTitle: "Feed your dragons",
    careText:
      "{name} is hungry: tap Feed to fill their belly. Dragons get hungry, bored and dirty as time goes by, even while you're away. This tile tends whatever it needs most: Feed, Play or Clean. Check in a few times a day, as a well-kept dragon flies at its best.",
    remindersTitle: "Reminders",
    remindersText: "I can send you a notification when {name} or any of your dragons needs care, so none goes hungry for long.",
    remindMe: "Remind me",
    notNow: "Not now",
    savedTitle: "Always saved",
    savedCloud: "Everything you do is saved as you play, on this phone and in {cloud}, so your stable survives a reinstall and follows you to a new phone.",
    savedLocal: "Everything you do is saved in this browser as you play. Clearing its site data starts a new stable.",
    gotIt: "Got it",
  },
  raceHint: {
    title: "Time for a first race!",
    text: "{name} is ready for the {league}. Tap Race to enter.",
    dismiss: "Dismiss",
  },
  wildLines: {
    booked: { one: "{count} on its way home", other: "{count} on their way home" },
    eggs: { one: "{count} egg", other: "{count} eggs" },
    heldOne: "{held}: no free slot",
    heldBoth: "{booked} and {eggs}: no free slot",
    full: "The stable is full: no free slot",
    allFit: "All {count} fit",
    someFit: "Only {fit} of {count} fit",
    sendAway: "{name} leaves the stable; calling it back takes {time}.",
  },
  wildBox: {
    onTheWay: "On the way · {time}",
    callHome: "Call home",
    callAll: "Call all home",
    callSome: "Call {count} home",
    empty: "No dragon lives in the wild. Send an adult there from its actions; it keeps its record and can be called home.",
    flyingHome: { one: "{name} is flying home.", other: "{count} dragons are flying home." },
  },
  ritualReadiness: {
    onTheWay: "On the way · {time}",
    inTheWild: "In the wild",
    notAdult: "{age}, not an adult",
    unfit: "{reason} · {time}",
    tired: "Tired · {time}",
    slumbering: "Slumbering · {time}",
    ready: "Ready",
    circleReady: "The circle is ready",
    pickAtLeast: { one: "Pick at least {count} adult", other: "Pick at least {count} adults" },
    inCircle: "{count} in the circle",
    notReady: { one: "{names} is not ready", other: "{names} are not ready" },
    readyIn: "ready in {time}",
    noSlot: "No slot for the egg",
    freeSlotFirst: "free a slot first",
    slumberLine: { one: "{names} slumbers for {time}.", other: "{names} slumber for {time}." },
  },
  awaySheet: {
    title: "While you were away",
    wentBy: "{time} went by · {date}",
    back: "Back to the stable",
    close: "Close",
    raced: "{name} finished {place}",
    racedDetail: "Race {race} over · {league}",
    eggReady: "An egg is ready to hatch",
    giftEgg: "Gift egg",
    needsYou: "{name} needs you",
    careDetail: "{mood} · {need} {value}%",
    readyToEvolve: "{name} is ready to evolve",
    evolveInto: { kid: "Into a kid", teen: "Into a teen", adult: "Into an adult" },
    arrived: "{name} is back from the wild",
    arrivedDetail: "Home in the stable",
    woke: "{name} woke from its slumber",
    wokeDetail: "Free to race again",
    fitFor: "Fit for the {league}",
    fitToRace: "Fit to race",
    healed: "{name} has healed",
    rested: "{name} is rested",
  },
  stableEvents: {
    evolve: "{name} is ready to evolve!",
    ready: "An egg is ready to hatch!",
    healed: "{name} has healed.",
    rested: "{name} can race again.",
    raced: "Race over: {name} finished {place}.",
    star: "{name} earned a star!",
  },
  profileSheet: {
    growthInfo: "It grows up with time alone: a kid becomes a teen in 4 hours, a teen an adult in 8. Care makes it stronger, not faster to grow.",
    racing: "Racing",
    racingInfo: "Its five racing stats. The shape comes from its body, the size from its stars; the dashed outline and the faint bars are the same dragon at five stars.",
    details: "Details",
    look: "Look",
    breathInfo: "Breathe plays it here in the yard. In a race it slows a rival, knocks it back and shakes it off its line, twice as hard on the element it is strong against and half as hard on the one it is weak against.",
    label: "Profile",
    close: "Close",
    tabs: { overview: "Overview", traits: "Traits", history: "History", egg: "Egg" },
    readyToHatch: "Ready to hatch",
    hatchesIn: "Hatches in {time}",
    onTheWayHome: "On the way home · {time}",
    onTheWayText: "Called back from the wild, it holds its slot and lands soon.",
    inTheWild: "In the wild",
    inTheWildText: "It cannot race or join a ritual until it is called home.",
    slumbering: "Slumbering · wakes in {time}",
    slumberingText: "It gave part of its soul at the altar and cannot race or join a ritual yet.",
    lineage: "Lineage",
    parent: "Parent {key}",
    goneParent: "No longer here",
    parents: "Parents",
    manyParents: "Each of the {count} gave part of its soul: every part and colour comes from one of them, the shape from all.",
    warmed: "Warmed",
    warmedValue: "{warms} / {limit}",
    hatchStars: { one: "Hatches at {stars} star", other: "Hatches at {stars} stars" },
    warmCaption: "Warm it once an hour, up to {limit} times: each warm brings hatching an hour closer and the dragon hatches ⅛ star stronger.",
    element: "Element",
    breathesWhenAwake: "Breathes again once it wakes.",
    breatheButton: "Breathe {element}",
    breathesAsTeen: "Breathes once it grows into a teen.",
    breath: "Breath",
    body: "Body",
    shape: "Shape",
    blendBoth: "Shape blends both parents.",
    blendAll: "Shape blends all {count} parents.",
    colours: "Colours",
    honours: "Trophies and medals",
    of: "of {count}",
    historyLine: "{division} · S{season} · R{race}",
    starts: "Starts",
    wins: "Wins",
    podiums: "Podiums",
    noRaces: "No races yet.",
    sendToWild: "Send to the wild",
    sendCaption: "Nothing is lost: you can call it back home any time.",
    reallySure: "<b>Are you really sure?</b> Your stable will be empty.",
    yesSend: "Yes, send it",
    keep: "Keep",
    flewOff: "{name} flew off to the wild.",
    stars: "Stars",
    starsHow: "Keep its needs high to grow the next star",
    starsTop: "Five stars: as strong as a dragon gets",
    starsInfo: "Stars are how strong it is, and every dragon can reach five. Every hour its needs stay high it grows a little stronger; neglect only stops it. It never loses a star and keeps them all as it grows up. Races don't add any.",
    strongAgainst: "Strong against",
    weakAgainst: "Weak against",
  },
  detailsScreen: {
    starsValue: "{stars} of {max}",
    statValue: "{now} / {top}",
    care: "Care",
    fatigue: "Fatigue",
    genes: "Genes",
    origin: "Origin",
    generation: "Generation",
    seed: "Seed",
  },
  raceEntryScreen: {
    pickInfo: "You ride one dragon a race. Racing tires it and can injure it; a tired dragon rests about a quarter of an hour before it races again.",
    fieldInfo: "Stars say how strong each dragon is and Fav is the best on paper. Form, the course and the flying decide the rest, so upsets happen.",
    seasonOver: "Season {number} is over. Start the next one from the league.",
    onAir: "Race {number} is on air with {name}. A race once started is flown to the finish.",
    yourDragonLower: "your dragon",
    backToRace: "Back to the race",
    yourDragon: "Your dragon",
    noneOfAge: {
      kid: "None of your dragons is a kid right now. Raise one to enter this league.",
      teen: "None of your dragons is a teen right now. Raise one to enter this league.",
      adult: "None of your dragons is an adult right now. Raise one to enter this league.",
    },
    field: "The field",
    starters: { one: "{count} starter, gate order", other: "{count} starters, gate order" },
    fav: "Fav",
    actions: { start: "Start race", pick: "Pick your dragon", noneReady: "No dragon ready", noneToRide: "No dragon to ride" },
    autopilot: "The race starts on Autopilot: your rider flies your dragon until you take the reins.",
  },
  leagueDetailScreen: {
    standingsInfo:
      "Divisions go Bronze, Silver, Gold, with stronger rivals each step up. Places score {points} points for the dragon's stable, whichever of yours races; after {races} races the top {up} go up and the bottom {down} go down. The Gold champion takes the league trophy.",
    zones: {
      up: "The top {up} go up to {upTo}.",
      upDown: "The top {up} go up to {upTo}, the bottom {down} go down to {downTo}.",
      champion: "The {division} champion is the league champion.",
      championDown: "The {division} champion is the league champion, the bottom {down} go down to {downTo}.",
    },
    seasonComplete: "Season {number} complete",
    noChampion: "No champion",
    trophyYours: "The trophy is yours! It is in the cabinet under More.",
    prizeEgg: { one: "A prize egg is in your stable, hatching at {stars} star.", other: "A prize egg is in your stable, hatching at {stars} stars." },
    ceremony: "Awards ceremony",
    ceremonyShort: "Ceremony",
    nextSeason: "Season {number} in {division}",
    nextRace: "Next race",
    raceOf: "Race {number} of {of}",
    rivals: "The same {count} {division} rival stables start every race of the season; you ride one of yours against them.",
    ready: { one: "{ready} of your {count} {age} ready to race.", other: "{ready} of your {count} {ages} ready to race." },
    backToRace: "Back to the race",
    enterRace: "Enter race",
    standings: "Standings",
    noRacesYet: "No races yet this season. Points per place: {points}.",
    thisSeason: "This season",
    racesEmpty: "The season's races appear here with their results and replays.",
    raceTitle: "Race {number} · {course}",
    yours: "(yours)",
    yourPlacings: "Yours: {placings}",
    results: "Results",
    watch: "Watch",
    watchLabel: "Watch race {number}",
    pastSeasons: "Past seasons",
    pastTitle: "Season {number} · {division}",
  },
  racesScreen: {
    noneOfAge: "No {age} in your stable",
    onAir: "On air",
    newSeason: "New season",
    enter: "Enter",
    best: { hold: "Yours: {place}", promote: "Yours: {place}, going up", relegate: "Yours: {place}, going down" },
    noPoints: "No points yet",
    season: "Season {number} · {next}",
    nextRace: "race {number} of {of} · {course}",
    complete: "complete",
    locked: "Locked",
    raceTitle: "{league} · Race {number}",
    raceDetail: "Season {season} · {division} · {course} · {date}",
    results: "Results",
    watch: "Watch",
    watchLabel: "Watch {league} race {number}",
    note: "A dragon races in the league of its age: kids, teens, then the Main Event.",
    recent: "Recent races",
    moreOnLeague: "Every race of the season is on its league's page.",
    empty: "Races your dragons fly appear here, newest first.",
  },
  resultsScreen: {
    title: "{league} · Race {number}",
    stamp: "{place}!",
    finish: "FINISH!",
    dnf: "DNF",
    podium: "Podium",
    photoFinish: "Photo finish",
    photoMargin: "{name} by {gap} s",
    gap: "+{gap} s",
    order: "Finishing order",
    yourDragons: "Your dragons",
    points: { one: "+{count} pt", other: "+{count} pts" },
    gone: "No longer in the stable.",
    starts: { one: "{count} start", other: "{count} starts" },
    wins: { one: "{count} win", other: "{count} wins" },
    podiums: { one: "{count} podium", other: "{count} podiums" },
    standingsAfter: "Standings after race {number} of {of}",
    seasonOver: "Season {number} is over",
    ceremony: "Awards ceremony",
    watchAgain: "Watch again",
    backToLeague: "Back to league",
  },
  ceremonyScreen: {
    title: "Awards ceremony",
    stamps: {
      champions: "Champions!",
      divisionChamps: "{division} champs!",
      promoted: "Promoted!",
      relegated: "Relegated",
      place: "{place}!",
      over: "Season over",
    },
    trophy: "The {league} trophy is yours!",
    trophyDetail: "{name} is the league champion.",
    medal: "{place}-place medal",
    medalDetail: "{name}, {place} in {division}.",
    prizeEgg: "A prize egg!",
    prizeDetail: { one: "A wild egg, nothing from your stable: it hatches at {stars} star.", other: "A wild egg, nothing from your stable: it hatches at {stars} stars." },
    prizeLeft: "{name}, your oldest, left for the wild to make room; you can call it home.",
    you: "You",
    noChampion: "No champion",
    finalStandings: "Final standings",
    nextSeason: "Season {number} in {division}",
    replay: "Replay ceremony",
    backToLeague: "Back to league",
  },
  leagueLook: {
    leagues: { kids: "Kids League", teens: "Teen League", adults: "Main Event" },
    divisions: { bronze: "Bronze", silver: "Silver", gold: "Gold" },
    courses: { canyon: "Canyon", valley: "Valley" },
    ageNouns: {
      kid: { one: "kid", other: "kids" },
      teen: { one: "teen", other: "teens" },
      adult: { one: "adult", other: "adults" },
    },
    theAges: { kid: "kids", teen: "teens", adult: "adults" },
    placing: "{place} {name}",
    seasonBegins: "{league}: season {number} begins in {division}!",
    locked: {
      tooYoung: "Your dragons are not old enough yet: the {league} is for {theAges}.",
      outgrown: "Your dragons have outgrown it: the {league} is for {theAges}.",
      noKid: "No kid in your stable yet: hatch an egg to race in the {league}.",
      none: "No {age} in your stable: the {league} is for {theAges}.",
    },
  },
  seasonOutcome: {
    noneRaced: "None of yours raced; you stay in {division}.",
    promoted: "Your stable finished {place}: promoted to {division}!",
    relegated: "Your stable finished {place}: relegated to {division}.",
    stayed: "Your stable finished {place}: you stay in {division}.",
    leagueChampion: "League champion",
    divisionChampion: "{division} champion",
  },
  honoursLook: {
    leagueChampion: "League champion",
    trophyDetail: "{league} · {division} · season {season}",
    medalTitle: "{place} in {division}",
    medalDetail: "{league} · season {season}",
    count: { one: "{count} honour", other: "{count} honours" },
  },
  standingsList: { stable: "Stable", wins: "W", points: "Pts" },
  stableView: {
    giftEgg: "Gift egg",
    starts: { one: "{count} start", other: "{count} starts" },
    wins: { one: "{count} win", other: "{count} wins" },
    podiums: { one: "{count} podium", other: "{count} podiums" },
    noRaces: "No races yet",
    gameDate: "Day {day} · {time}",
  },
  blockText: {
    onAir: "On air",
    tired: "Tired",
    slumbering: "Slumbering",
    wrongAge: "Wrong age",
    stableFull: "The stable is full",
    injury: { wing: "Strained wing", leg: "Sore leg", membrane: "Torn membrane" },
    ritual: {
      needTwo: "Pick at least two dragons",
      notInStable: "{name} is not in the stable",
      adultsOnly: "Only adults can take part",
      unfit: "{name}: {reason}",
      slumbering: "{name} is slumbering",
    },
    wild: {
      alreadyWild: "Already in the wild",
      notInStable: "Not in the stable",
      adultsOnly: "Only adults can live in the wild",
      notWild: "Not in the wild",
      onTheWay: "Already on the way home",
    },
  },
  cloudSave: { icloud: "iCloud", google: "your Google account" },
  altarScreen: {
    skip: "Skip",
    custodian: "Custodian",
    emptyPlace: "Empty place {n}, pick an adult",
    leavePlace: "{name}, tap to leave the circle",
    growing: "Growing up: {list}.",
    growingOne: "{name} ({age}, adult in {time})",
    eggLabel: "An egg lies on the altar",
    silentLabel: "The stones are silent",
    eggStamp: "An egg!",
    silentStamp: "Silence",
    eggTitle: "An egg lies on the altar!",
    silentTitle: "The stones are silent...",
    eggText: "It is in the stable, keeping its slot.",
    silentText: "No egg this time; the odds were {odds}.",
    seeEgg: "See the egg",
    backToAltar: "Back to the altar",
    needsTwo: "The altar needs two adults",
    onlyAdult: "{name} is your only adult at home. A ritual takes two or more.",
    noAdults: "Your stable has no adults at home. A ritual takes two or more.",
    backToStable: "Back to the stable",
    chance: "chance of an egg",
    tradeoff: "More parents make an egg likelier but less predictable: each part and colour comes whole from one of them.",
    begin: "Begin",
    adults: "Adults",
    cannotJoin: "Cannot join",
    circleFull: "The circle is full. Tap one in it to make room.",
    oddsInfo: "Two parents give a {base}% chance; each extra parent adds less than the last, up to {top}% with {most}. Egg or not, every parent then slumbers, {success} hours after an egg and {failure} after silence.",
    adultsInfo: "An egg hatches at half its parents' average stars. It takes every part, its element and every colour whole from one parent, now and then mutating into something no parent shows, and blends its shape from all.",
  },
  broadcastScreen: {
    catchingUp: "Back to the broadcast…",
    progress: "Course flown",
    view: "Race broadcast",
    leave: "Leave the race",
    leaderboard: "Leaderboard",
    raceControl: "Race control",
    camera: "Camera",
    cameraIs: "Camera: {camera}",
    cameras: { director: "Director", rider: "Rider", free: "Free", chase: "Chase" },
    pause: "Pause",
    play: "Play",
    playbackSpeed: "Playback speed",
    skip: "Skip to the finish",
    riding: "Riding",
    autopilot: "Autopilot",
    takeReins: "Take the reins",
    yourDragon: "Your dragon",
    title: "{league} · Race {race}",
    season: "Season {season}",
    exhibition: "Exhibition",
    raceSeed: "Race seed {seed}",
    sub: "{sub} · {course}",
    finished: "Finished",
    loading: { back: "Back to the race…", canyon: "Carving the canyon…", valley: "Shaping the valley…" },
    injured: "{name}: {injury} after the race.",
  },
  commentaryLine: {
    grid: { one: "{count} dragon lines up on the grid…", other: "{count} dragons line up on the grid…" },
    start: { valley: "And they're off into the valley!", canyon: "And they're off into the canyon!", course: "And they're off into the course!" },
    wins: "{who} wins it!",
    finish: "{who} crosses the line {place}.",
    takesLead: "{who} takes the lead from {other}!",
    passes: "{who} passes {other} for {place}.",
    miss: "{who} misses a gate!",
    dnf: "{who} will not finish.",
    land: {
      water: "{who} splashes down in the water!",
      mud: "{who} lands in the mud!",
      sand: "{who} lands on the sand!",
      dirt: "{who} touches down!",
    },
    thermal: "{who} rides a thermal.",
    hit: { fire: "{other}'s fire catches {who}!", nature: "{other}'s thorns snag {who}!", earth: "{other}'s sandblast knocks {who} back!", storm: "{other}'s lightning jolts {who}!", water: "{other}'s water jet soaks {who}!" },
    breath: { fire: "{who} breathes fire at {other}!", nature: "{who} lashes thorns at {other}!", earth: "{who} blasts sand at {other}!", storm: "{who} breathes lightning at {other}!", water: "{who} blasts water at {other}!" },
    superEffective: { fire: "Super effective! {other}'s fire burns through {who}!", nature: "Super effective! {other}'s roots crack {who}!", earth: "Super effective! {other} grounds {who}!", storm: "Super effective! {other}'s lightning shocks {who}!", water: "Super effective! {other} douses {who}!" },
    resisted: "{who} shrugs off {other}'s breath.",
    form: { perfect: "{who} is in perfect shape today!", off: "{who} looks a little off today." },
  },
  countdownOverlay: { grid: "Starting grid", go: "Go!" },
  effectLook: { slow: "Slowed", daze: "Dazed" },
  riderControls: {
    hint: "Drag to steer",
    breathe: "Breathe {element}",
  },
  raceReins: {
    finished: "Finished",
    gate: "Gate {gate}/{gates}",
  },
  reinsTour: {
    autopilotTitle: "Autopilot",
    autopilotText: "The race starts on Autopilot: your rider flies {name} for you, picking the line and breathing at the right rivals. Sit back and enjoy the show.",
    skipTitle: "Not your thing?",
    skipText: "No need to watch every race: tap the chequered flag whenever you like and your rider takes {name} to the finish for you, straight to the results.",
    reinsTitle: "Take the reins",
    reinsText: "Or take over and fly {name} yourself: tap Take the reins to pick the line and breathe when you choose. You can hand back to Autopilot whenever you like.",
    reinsKeys: "Or press R on a keyboard",
    steerTitle: "Steer",
    steerText: "Drag anywhere on the race: sideways turns, up climbs, down dives. Let go and your dragon goes back to its racing line.",
    steerKeys: "Arrows or WASD on a keyboard",
    gaugesTitle: "Speed and gates",
    gaugesText: "Your speed and the next gate. Fly through every gate in order, through the middle for a little burst: the arrow marks the next one.",
    backTitle: "Back to Autopilot",
    backText: "Tap Autopilot to let your rider fly again, and take the reins back whenever you like.",
    backKeys: "Or press R on a keyboard",
    ride: "Ride!",
    breathTitle: "Breath",
    breathText: "{breath} hits the rival ahead or alongside, then recharges. Each element beats one other: line up behind the rival yours is strong against.",
    breathKeys: "Space, F or E breathes",
  },
  careNames: {
    needs: { fullness: "Fed", happiness: "Happy", cleanliness: "Clean", exercise: "Exercised", affection: "Affection" },
    actions: { feed: "Feed", play: "Play", clean: "Clean", exercise: "Exercise", groom: "Groom" },
  },
  minigames: {
    done: "Done",
    best: "Best {score}",
    record: "New best! {name} gets a full top-up",
    feed: { title: "Snack toss", throw: "Drag to aim, let go to throw", grass: "Missed! It eats it off the grass", lost: "Lost it!", last: "One more miss and snack time is over" },
    clean: { title: "Bath time", sponge: "Scrub the mud off", rinse: "Rinse the suds away", swing: "Now the other side!" },
    exercise: { title: "Workout", ready: "Tap on the beat!", pushup: "Push-ups! Tap on the beat", squat: "Squats! Tap on the beat", jack: "Wing jacks! Tap on the beat", crunch: "Tail crunches! Tap on the beat", flop: "Flat out!" },
    groom: { title: "Scratch spot", search: "Stroke it to find the itchy spot", warm: "Warmer… it's leaning in", bliss: "Right there! Keep scratching", found: "Bliss! Now it itches somewhere else", snort: "Not the nose!", record: "New best! {name} loves you a little more" },
    volleyball: { title: "Volleyball", serve: "Here it comes!", catch: "Catch the ball!", throw: "Flick it back up", dropped: "Dropped it!", whiffed: "Whiff! It missed" },
    fetch: { title: "Fetch", throw: "Drag up to aim, let go to throw", fetch: "Fetch!", stick: "Here it comes with the stick", log: "That's a whole log…", bone: "Whose bone is that?", plop: "Plop. Not even worth chasing" },
    warm: { title: "Warm up", rub: "Rub the egg in circles", keep: "Just right, keep it there!", hot: "Too hot! Gently", fizzle: "Fizzled! Gentler this time", cosy: "Toasty!", record: "New best warm!" },
  },
  formatDuration: { d: "{count}d", h: "{count}h", m: "{count}m", s: "{count}s" },
  hitFloats: { super: "Super effective!", resisted: "Resisted", hit: "Hit!" },
  formLook: {
    perfect: "Perfect shape",
    off: "Off shape",
    line: { perfect: "{name} is in perfect shape today", off: "{name} is a little off today" },
    info: {
      perfect: "Race-day form: in perfect shape, it flies its next race a touch faster off the line and at top speed.",
      off: "Race-day form: a little off, it flies its next race a touch slower off the line and at top speed.",
    },
  },
};
