export const it = {
  language: { label: "Lingua" },
  breathReveal: {
    eyebrow: "Nuova mossa: il soffio",
    titles: {
      fire: "{name} sputa fuoco!",
      storm: "{name} scaglia fulmini!",
      nature: "{name} scaglia spine!",
      earth: "{name} spara sabbia e roccia!",
      water: "{name} soffia acqua!",
    },
    elements: { fire: "Fuoco", nature: "Natura", earth: "Terra", storm: "Tempesta", water: "Acqua" },
    howTo: "Quando prendi le redini in gara, tocca <b>{element}</b> appena un rivale ti vola davanti o di fianco: il colpo lo rallenta, lo respinge e lo fa sbandare, il doppio sull'elemento che {name} batte.",
    autopilot: "Col pilota automatico, {name} soffia da solo.",
    again: "Ancora!",
    done: "Capito!",
  },
  infoTip: {
    label: "Cos'è?",
    about: "Info su {about}",
  },
  app: {
    back: "Indietro",
    saveFailed: "Non riesco a salvare la tua stalla su questo dispositivo.",
    documentTitle: "Dragons! — {title}",
    logoLabel: "Dragons!, torna alla stalla",
    screensLabel: "Schermate",
  },
  routes: {
    welcome: "Benvenuti",
    stable: "Stalla",
    away: "Mentre eri via",
    profile: "Profilo",
    details: "Dettagli",
    lineage: "Discendenza",
    altar: "Altare",
    race: "Gara",
    races: "Gare",
    results: "Risultati",
    ceremony: "Premiazione",
    more: "Impostazioni",
    ownerProfile: "Profilo",
    league: "Lega",
    raceEntry: "Iscrizione",
    exhibition: "Esibizione",
    exhibitionRace: "Gara di esibizione",
    editor: "Editor",
  },
  nav: { stable: "Stalla", race: "Gare", altar: "Altare", more: "Impostazioni" },
  loadingScreen: { waking: "La stalla si sta svegliando…" },
  genes: {
    labels: {
      body: "Lunghezza del busto",
      wingspan: "Apertura alare",
      neck: "Lunghezza del collo",
      tail: "Lunghezza della coda",
      horns: "Misura di corna e creste",
      spines: "Altezza della cresta",
      scales: "Colore delle scaglie",
      wings: "Colore delle ali",
      underside: "Colore del ventre",
      legs: "Lunghezza delle zampe",
      thighs: "Spessore delle cosce",
      head: "Testa",
      headgear: "Corna e creste",
      legShape: "Zampe",
      wingFingers: "Dita delle ali",
      feet: "Piedi",
      tailTip: "Punta della coda",
      hindWings: "Ali posteriori",
      breath: "Soffio",
      eyes: "Colore degli occhi",
      metal: "Manto metallico",
      mane: "Criniera",
      markings: "Manto",
    },
    choices: {
      colours: { crimson: "Cremisi", ember: "Brace", rust: "Ruggine", coral: "Corallo", tangerine: "Mandarino", amber: "Ambra", gold: "Oro", sand: "Sabbia", lime: "Lime", moss: "Muschio", fern: "Felce", jade: "Giada", forest: "Foresta", mint: "Menta", teal: "Verde petrolio", turquoise: "Turchese", sky: "Cielo", azure: "Azzurro", cobalt: "Cobalto", navy: "Blu notte", steel: "Acciaio", violet: "Viola", plum: "Prugna", lavender: "Lavanda", rose: "Rosa", magenta: "Magenta", ivory: "Avorio", ash: "Cenere", slate: "Ardesia", black: "Nero", bronze: "Bronzo", chocolate: "Cioccolato" },
      head: { toothed: "Dentata", beaked: "A becco", blunt: "Tozza", needle: "Muso ad ago", viper: "Da vipera" },
      headgear: { swept: "Corna all'indietro", ram: "Corna d'ariete", frill: "Gorgiera", crown: "Corona di spine", antlers: "Palchi" },
      legShape: { raptor: "Da rapace", feathered: "Piumate", armoured: "Corazzate", spurred: "Con speroni" },
      wingFingers: { claws: "Artigli uncinati", long: "Dita lunghe", stubby: "Dita tozze", bony: "Solo ossa", spikes: "Spuntoni" },
      feet: {
        raptor: "Artigli da rapace",
        eagle: "Presa d'aquila",
        heavy: "Cuscinetti robusti",
        webbed: "Palmati",
        sickle: "Artiglio a falce",
        perching: "Presa da posatoio",
        gecko: "Cuscinetti da geco",
      },
      tailTip: { plain: "Affusolata", spade: "A picca", fan: "A ventaglio", club: "A mazza", stinger: "Pungiglione", fin: "Pinna biforcuta" },
      hindWings: { none: "Nessuna", membrane: "Ali posteriori", feathered: "Ali posteriori piumate" },
      breath: { fire: "Fuoco", nature: "Natura", earth: "Terra", storm: "Tempesta", water: "Acqua" },
      eyes: { gold: "Oro", amber: "Ambra", jade: "Giada", ice: "Ghiaccio", blood: "Sangue", violet: "Viola", moonstone: "Pietra di luna" },
      metal: { none: "Nessuno", gold: "Oro", silver: "Argento", goldSilver: "Oro e argento", silverGold: "Argento e oro" },
      mane: { spikes: "Spine", element: "Criniera elementale" },
      markings: { none: "Nessuno", leopard: "Macchie di leopardo", zebra: "Strisce di zebra", cow: "Pezzatura di mucca" },
    },
  },
  riderLookFields: {
    fields: {
      build: "Corporatura",
      ears: "Orecchie",
      skin: "Carnagione",
      eyes: "Colore degli occhi",
      hair: "Capelli",
      facialHair: "Barba",
      hairColor: "Colore dei capelli",
      marks: "Segni",
      hat: "Copricapo",
      goggles: "Occhialoni",
      scarf: "Sciarpa",
      gloves: "Guanti",
      boots: "Stivali",
      breeches: "Pantaloni",
    },
    options: {
      build: { slim: "Snella", athletic: "Atletica", average: "Media", hourglass: "A clessidra", broad: "Robusta", stocky: "Tarchiata" },
      ears: { round: "Tonde", pointed: "A punta", long: "Elfiche" },
      skin: {
        porcelain: "Porcellana",
        rosy: "Rosata",
        fair: "Chiara",
        light: "Luminosa",
        tan: "Ambrata",
        golden: "Dorata",
        olive: "Olivastra",
        bronze: "Bronzea",
        brown: "Bruna",
        umber: "Terra d'ombra",
        deep: "Scura",
        ebony: "Ebano",
      },
      eyes: { brown: "Castani", dark: "Scuri", hazel: "Nocciola", amber: "Ambra", green: "Verdi", blue: "Azzurri", grey: "Grigi", violet: "Viola" },
      hair: {
        bald: "Calvo",
        buzz: "Rasati",
        short: "Corti",
        quiff: "Ciuffo",
        curly: "Ricci",
        spiky: "A punte",
        mohawk: "Cresta",
        bob: "Caschetto",
        ponytail: "Coda di cavallo",
        braid: "Treccia",
        pigtails: "Codini",
        bun: "Chignon",
        topknot: "Crocchia alta",
        long: "Lunghi",
        afro: "Afro",
      },
      facialHair: { none: "Nessuna", stubble: "Incolta", moustache: "Baffi", goatee: "Pizzetto", beard: "Barba piena", braided: "Barba intrecciata" },
      hairColor: {
        black: "Neri",
        espresso: "Caffè",
        brown: "Castani",
        chestnut: "Castagna",
        auburn: "Ramati",
        ginger: "Rossi",
        strawberry: "Biondo fragola",
        blond: "Biondi",
        platinum: "Platino",
        grey: "Grigi",
        white: "Bianchi",
        teal: "Verde acqua",
        blue: "Blu",
        purple: "Viola",
        pink: "Rosa",
        green: "Verdi",
      },
      marks: { none: "Nessuno", freckles: "Lentiggini", blush: "Guance rosse", paint: "Pittura" },
      hat: { cap: "Caschetto della casacca", aviator: "Cuffia da volo", bandana: "Bandana", circlet: "Diadema", pointed: "Cappello a punta", horned: "Elmo con le corna", none: "Nessuno" },
      goggles: { smoke: "Fumé", amber: "Ambra", emerald: "Smeraldo", sky: "Cielo", rose: "Rosa", mirror: "Specchio d'oro" },
      scarf: { none: "Nessuna", short: "Corta", long: "Lunga" },
      gloves: { leather: "Cuoio", black: "Neri", white: "Bianchi", silks: "Colore casacca" },
      boots: { black: "Neri", brown: "Marroni", tan: "Cuoio chiaro", white: "Bianchi", silks: "Colore casacca" },
      breeches: { white: "Bianchi", cream: "Panna", tan: "Beige", grey: "Grigi", black: "Neri", silks: "Colore casacca" },
    },
  },
  silksFields: {
    pattern: "Disegno",
    roles: { body: "Base", accent: "Secondario", trim: "Profili" },
    none: "Nessuno",
    patterns: {
      plain: "Tinta unita",
      hoops: "A cerchi",
      stripes: "A righe",
      halves: "Divisa a metà",
      quarters: "A quarti",
      sash: "Con fascia",
      crossbelts: "Bretelle incrociate",
      chevrons: "A galloni",
      checks: "A scacchi",
      diamonds: "A rombi",
      braces: "Con bretelle",
    },
    colors: {
      white: "Bianco",
      cream: "Panna",
      silver: "Argento",
      grey: "Grigio",
      black: "Nero",
      brown: "Marrone",
      maroon: "Bordeaux",
      scarlet: "Scarlatto",
      coral: "Corallo",
      orange: "Arancione",
      gold: "Oro",
      yellow: "Giallo",
      lime: "Lime",
      emerald: "Smeraldo",
      forest: "Verde bosco",
      mint: "Menta",
      teal: "Verde acqua",
      sky: "Azzurro",
      royal: "Blu reale",
      navy: "Blu notte",
      lavender: "Lavanda",
      purple: "Viola",
      pink: "Rosa",
    },
  },
  pickerFields: { previous: "{field}: precedente", next: "{field}: successivo" },
  riderMaker: {
    name: "Nome",
    randomName: "Un altro nome",
    random: "Sorprendimi",
    groups: { body: "Corpo", face: "Viso", hair: "Capelli", accessories: "Copricapo e accessori", jacket: "Casacca", kit: "Pantaloni, guanti e stivali" },
  },
  welcomeScreen: {
    stableHand: "Garzone di stalla",
    nameLine: "Eccoti qui! Sei tu a cavalcare ogni drago della tua stalla. Come ti chiami?",
    nameNext: "Sono io!",
    meetLine: "Allora, {owner}, questi tre cuccioli cercano casa e uno di loro lo allevi tu. Toccane uno qui sotto per conoscerlo.",
    pickLines: {
      topSpeed: "{kid} ha un corpo lungo e affusolato, fatto per i rettilinei. Allevalo, o conoscine un altro qui sotto.",
      acceleration: "{kid} ha ali grandi e riprende velocità in un lampo. Allevalo, o conoscine un altro qui sotto.",
      handling: "{kid} ha una coda lunga e gira su una moneta, fatto per i canyon. Allevalo, o conoscine un altro qui sotto.",
      weight: "{kid} è grosso e robusto, difficile da spostare. Allevalo, o conoscine un altro qui sotto.",
      breath: "{kid} ha un gran copricapo: un lottatore nato, appena saprà soffiare. Allevalo, o conoscine un altro qui sotto.",
    },
    kids: "I tre cuccioli",
    allKids: "Tutti e tre",
    allKidsSub: "Fianco a fianco",
    pickFirst: "Prima conosci un cucciolo",
    raise: "Alleva {name}",
    gift: "Un regalo!",
    giftLine:
      "Ogni nuovo proprietario riceve anche un uovo: tienilo al caldo e ne uscirà un cucciolo. Quando {name} sarà in forma, iscrivilo alla Lega Cuccioli in Gare. Vola col pilota automatico finché non prendi tu le redini: ti faccio vedere come alla tua prima gara.",
    giftNext: "Alla stalla",
  },
  ownerProfileScreen: {
    caption: "Cavalchi ogni tuo drago con questa casacca.",
  },
  moreScreen: {
    profile: "Profilo",
    trophies: "Trofei",
    noTrophies: "Vinci una stagione in Oro per conquistare il trofeo di una lega.",
    medals: "Medaglie",
    noMedals: "Chiudi una stagione sul podio di una divisione qualsiasi per vincere una medaglia.",
    settings: "Aspetto e lingua",
    reminders: "Promemoria",
    remindersRow: "Promemoria di cura",
    remindersOn: "Sì",
    remindersOff: "No",
    remindersWhen: "Al massimo due al giorno quando i tuoi draghi hanno bisogno di cure, e mai tra le 23:00 e le 06:00.",
    remindersOffText: "Nessun promemoria: passa tu a trovare i tuoi draghi.",
    remindersAsk: "Il telefono non ha ancora permesso i promemoria.",
    remindersAllow: "Permetti i promemoria",
    remindersDenied: "Le notifiche di Dragons! sono spente nelle impostazioni del telefono.",
    remindersOpenSettings: "Apri le impostazioni",
    remindersWeb: "I promemoria arrivano con le app per iPhone e Android.",
    detail: "Dettaglio",
    details: { light: "2×", full: "4×" },
    sound: "Suono",
    soundEffects: "Effetti",
    soundMusic: "Musica",
    developer: "Sviluppatore",
    gameClock: "Orologio di gioco",
    gameClockSpeed: "Velocità dell'orologio di gioco",
    exhibition: "Campo di esibizione",
    newStable: "Nuova stalla",
    confirmReset: "Ricominci davvero?",
    legal: "Note legali",
    privacy: "Informativa sulla privacy",
    terms: "Termini e condizioni",
  },
  parentKeys: { mutation: "Mutazione", aParent: "Un genitore" },
  ritualTimeline: {
    raise: [
      "Fatti un po' indietro. Le antiche pietre si stanno svegliando.",
      "Silenzio, ora. Le pietre ricordano ogni anima che è passata di qui.",
      "Resta accanto a me. Il cerchio ci sta ascoltando.",
    ],
    breath: ["Ora, tutti insieme: soffiate!", "Soffiate, tutti quanti, come uno solo!", "Metteteci tutto il vostro fuoco, insieme!"],
    success: [
      "Un'anima nuova è arrivata. Accoglila a casa.",
      "Ecco: un uovo, ancora caldo di pietra. Il cerchio ha risposto.",
      "Guarda! Stanotte le pietre ci hanno donato un'anima.",
    ],
    failure: [
      "Stanotte le pietre tengono per sé i loro segreti. Fai riposare i tuoi draghi e torna più avanti.",
      "Stavolta nessuna anima ha risposto. Non è colpa di nessuno: è il cerchio a scegliere.",
      "Solo nebbia, stanotte. Falli riposare bene: le pietre ascolteranno di nuovo.",
    ],
  },
  lineageScreen: {
    pair: "{a} × {b}",
    noLongerHere: "non è più qui",
    inTheWild: "in natura",
    inStable: "nella tua stalla",
    childOf: "Discende da {names}",
    seedBorn: "Nato dal seme",
    seedBornTag: "nato dal seme",
    gen: "Gen. {gen}",
    parentLabel: "Genitore {key}, {name}, apri il profilo",
    parentGoneLabel: "Genitore {key}, {name}",
    childLabel: "{name}, apri il profilo",
    ritualOf: "Un rituale a {count}",
    bodyParts: "Parti del corpo",
    mutationTitle: { one: "Una mutazione!", other: "{count} mutazioni!" },
    mutationText: "{traits}: qualcosa che nessun genitore aveva.",
    partsCaption: {
      two: "Ogni parte arriva intera da un genitore; ogni tanto una muta in qualcosa che nessuno dei due aveva.",
      many: "Ogni parte arriva intera da un genitore; ogni tanto una muta in qualcosa che nessun genitore aveva.",
    },
    colours: "Colori",
    coloursCaption: {
      two: "Scaglie, ali e ventre prendono ciascuno il colore intero da un genitore, o mutano in uno che nessuno dei due aveva. La forma del corpo è un mix di entrambi.",
      many: "Scaglie, ali e ventre prendono ciascuno il colore intero da un genitore, o mutano in uno che nessun genitore aveva. La forma del corpo è un mix di tutti e {count}.",
    },
    seedBornText: "Nessun genitore conosciuto: parti, colori e forma vengono tutti dal suo seme. I suoi piccoli saranno Gen. 1.",
  },
  editorScreen: {
    tabs: { dragon: "Drago", genes: "Geni", rider: "Fantino",},
    flightMode: "Modalità di volo",
    previous: "Partecipante precedente",
    next: "Partecipante successivo",
    editor: "Editor",
    name: "Nome",
    seed: "Seme",
    generate: "Genera",
    age: "Età",
    harness: "Bardatura",
    off: "No",
    on: "Sì",
    harnessCaption: "La bardatura cambia solo l'aspetto; la gara resta la stessa.",
    genomeControls: "Controlli del genoma",
    shape: "Corpo",
    colours: "Colori",
    resetGenes: "Ripristina i geni dal seme",
    riderCaption: "Il fantino cambia solo l'aspetto; la gara resta la stessa.",
    reroll: "Rigenera",
    pause: "Metti in pausa l'animazione",
    play: "Avvia l'animazione",
    strength: "Stelle",
  },
  fieldScreen: {
    courseSeed: "Seme del percorso",
    raceSeed: "Seme della gara",
    moveUp: "Sposta su {name}",
    moveDown: "Sposta giù {name}",
    remove: "Rimuovi {name}",
    race: "Gara",
    course: "Percorso",
    age: "Età",
    caption: "I fantini cambiano solo l'aspetto. I semi e la griglia decidono il risultato.",
    theField: "I partecipanti",
    fieldCount: "{count} / {max}, P1 in pole",
    add: "Aggiungi drago",
    shuffle: "Mescola la griglia",
    start: "Via alla gara",
    stars: "{stars}★",
  },
  dragonStatus: {
    fullyGrown: "Crescita completa",
    readyToEvolve: "Pronto a diventare {age}",
    growsIn: "{age} tra {time}",
    healsIn: "guarisce tra {time}",
    tired: "Stanco",
    restedIn: "riposato tra {time}",
    fitTired: "In forma, un po' stanco",
    rested: "Riposato",
  },
  dragonAge: { kid: "Cucciolo", teen: "Giovane", adult: "Adulto" },
  stableHome: {
    rename: "Rinomina",
    name: "Nome",
    roster: "I tuoi draghi",
    yourStable: "La tua stalla",
    slots: "{used} su {total}",
    wildTab: "Nella natura · {count}",
    egg: "Uovo",
    ready: "Pronto!",
    freeSlot: "Posto libero",
    bookedLabel: "{name}, sta tornando a casa",
    onTheWay: "In arrivo",
    onTheWayHome: "Sta tornando a casa · {time}",
    inTheWild: "Nella natura",
    emptyWild: "Non c'è nessun drago a casa. Richiamane uno dalla natura.",
    emptyStable: "La stalla è vuota. Ricominciane una da Altro.",
    profile: "Profilo",
    warm: "Scalda",
    warmCount: "Scalda {count}/{limit}",
    race: "Gareggia",
    evolve: "Evolvi",
    pop: "Pop!",
    crack: "Crac!",
    hatched: "È nato!",
    grown: { teen: "Giovane!", adult: "È diventato grande!" },
    warmGain: "Un'ora prima, ⅛ ★ più forte",
  },
  yardHatch: { hatch: "Schiudi", again: "Ancora!" },
  mood: {
    needs: {
      fullness: "Affamato!",
      happiness: "Annoiato…",
      cleanliness: "Vuole un bagnetto",
      exercise: "Irrequieto",
      affection: "Ti sente lontano",
    },
    readyToHatch: "Sta per schiudersi!",
    onTheWayHome: "Sta tornando a casa",
    inTheWild: "Nella natura",
    onAir: "In onda",
    slumbering: "Dorme · si sveglia tra {time}",
    readyToEvolve: "Pronto a evolversi!",
    tired: "Stanco",
    readyToRace: "Pronto a gareggiare!",
  },
  needNotifications: {
    fullness: "{name} ha fame!",
    happiness: "{name} si annoia…",
    cleanliness: "{name} ha bisogno di un bagnetto",
    exercise: "{name} non sta più fermo",
    affection: "{name} ti sente lontano",
    warm: "Il tuo uovo è pronto per essere scaldato",
    hatch: "Il tuo uovo è pronto a schiudersi!",
    missed: "{name} sente la tua mancanza!",
    missedEgg: "Il tuo uovo sente la tua mancanza!",
    anEgg: "il tuo uovo",
    alsoOne: "Anche {name} ha bisogno di te.",
    alsoTwo: "Anche {a} e {b} hanno bisogno di te.",
    alsoMany: "Anche {name} e altri {count} hanno bisogno di te.",
  },
  stars: { label: "{count} stelle su {max}", reach: "{count} stelle su {max}, verso la {reachable}ª" },
  statBars: {
    topSpeed: "Velocità massima",
    acceleration: "Accelerazione",
    handling: "Manovrabilità",
    weight: "Peso",
    breath: "Soffio",
    breathOff: "Soffierà quando diventa un giovane",
    hints: { topSpeed: "Un busto lungo e affusolato: il più veloce sui rettilinei", acceleration: "Ali grandi: torna in fretta alla sua velocità dopo un colpo o una spinta", handling: "Una coda lunga: curve strette senza perdere velocità", weight: "La sua mole: vince gli scontri e regge i soffi, ma parte più lento", breath: "Un copricapo grande: colpi più forti che si ricaricano prima" },
  },
  slotMeter: { label: "Stalla", slots: "{used} posti su {total}" },
  coachMarks: { next: "Avanti", skip: "Salta", keepWatching: "Continua a guardare" },
  stableTour: {
    careTitle: "Dai da mangiare ai tuoi draghi",
    careText:
      "{name} ha fame: tocca Dai da mangiare per riempirgli la pancia. Col passare del tempo i draghi hanno fame, si annoiano e si sporcano, anche quando non ci sei. Questo pulsante pensa a ciò che serve di più: Dai da mangiare, Gioca o Pulisci. Passa a trovarlo qualche volta al giorno: un drago ben accudito vola al meglio.",
    remindersTitle: "Promemoria",
    remindersText: "Posso mandarti una notifica quando {name} o un altro dei tuoi draghi ha bisogno di cure, così nessuno resta a pancia vuota a lungo.",
    remindMe: "Ricordamelo",
    notNow: "Non ora",
    savedTitle: "Sempre salvato",
    savedCloud: "Tutto quello che fai si salva mentre giochi, su questo telefono e su {cloud}, così la tua stalla resta anche se reinstalli il gioco e ti segue su un nuovo telefono.",
    savedLocal: "Tutto quello che fai si salva in questo browser mentre giochi. Se ne cancelli i dati del sito, ricominci con una stalla nuova.",
    gotIt: "Capito!",
  },
  raceHint: {
    title: "È ora della prima gara!",
    text: "{name} è pronto a gareggiare nella {league}. Tocca Gareggia per iscriverlo.",
    dismiss: "Chiudi",
  },
  wildLines: {
    booked: { one: "{count} sta tornando a casa", other: "{count} stanno tornando a casa" },
    eggs: { one: "{count} uovo", other: "{count} uova" },
    heldOne: "{held}: nessun posto libero",
    heldBoth: "{booked} e {eggs}: nessun posto libero",
    full: "La stalla è piena: nessun posto libero",
    allFit: "C'è posto per tutti e {count}",
    someFit: "C'è posto solo per {fit} su {count}",
    sendAway: "{name} lascia la stalla; per richiamarlo ci vogliono {time}.",
  },
  wildBox: {
    onTheWay: "In arrivo · {time}",
    callHome: "Richiama",
    callAll: "Richiamali tutti",
    callSome: "Richiamane {count}",
    empty: "Nessun drago vive nella natura. Puoi mandarci un adulto dalle sue azioni: tiene il suo palmarès e puoi richiamarlo quando vuoi.",
    flyingHome: { one: "{name} sta volando a casa.", other: "{count} draghi stanno volando a casa." },
  },
  ritualReadiness: {
    onTheWay: "In arrivo · {time}",
    inTheWild: "Nella natura",
    notAdult: "{age}, non ancora adulto",
    unfit: "{reason} · {time}",
    tired: "Stanco · {time}",
    slumbering: "Dorme · {time}",
    ready: "Pronto",
    circleReady: "Il cerchio è pronto",
    pickAtLeast: { one: "Scegli almeno {count} adulto", other: "Scegli almeno {count} adulti" },
    inCircle: "{count} nel cerchio",
    notReady: { one: "{names} non è pronto", other: "{names} non sono pronti" },
    readyIn: "pronti tra {time}",
    noSlot: "Non c'è posto per l'uovo",
    freeSlotFirst: "prima libera un posto",
    slumberLine: { one: "{names} dormirà per {time}.", other: "{names} dormiranno per {time}." },
  },
  awaySheet: {
    title: "Mentre non c'eri",
    wentBy: "Sono passati {time} · {date}",
    back: "Torna alla stalla",
    close: "Chiudi",
    raced: "{name} è arrivato {place}",
    racedDetail: "Gara {race} finita · {league}",
    eggReady: "Un uovo sta per schiudersi",
    giftEgg: "Uovo in regalo",
    needsYou: "{name} ha bisogno di te",
    careDetail: "{mood} · {need} {value}%",
    readyToEvolve: "{name} è pronto a evolversi",
    evolveInto: { kid: "Diventa cucciolo", teen: "Diventa giovane", adult: "Diventa adulto" },
    arrived: "{name} è tornato dalla natura",
    arrivedDetail: "Di nuovo a casa nella stalla",
    woke: "{name} si è svegliato",
    wokeDetail: "Può di nuovo gareggiare",
    fitFor: "Pronto per la {league}",
    fitToRace: "Pronto a gareggiare",
    healed: "{name} è guarito",
    rested: "{name} si è riposato",
  },
  stableEvents: {
    evolve: "{name} è pronto a evolversi!",
    ready: "Un uovo sta per schiudersi!",
    healed: "{name} è guarito.",
    rested: "{name} può gareggiare di nuovo.",
    raced: "Gara finita: {name} è arrivato {place}.",
    star: "{name} ha conquistato una stella!",
  },
  profileSheet: {
    growthInfo: "Cresce solo col tempo: un cucciolo diventa giovane in 4 ore, un giovane adulto in 8. Le cure lo rendono più forte, non lo fanno crescere prima.",
    racing: "In gara",
    racingInfo: "Le sue cinque statistiche di gara. La forma viene dal fisico, la grandezza dalle stelle; il contorno tratteggiato e le barre chiare sono lo stesso drago a cinque stelle.",
    details: "Dettagli",
    look: "Aspetto",
    breathInfo: "Con Soffia lo vedi qui nel cortile. In gara rallenta un rivale, lo respinge e lo fa sbandare, il doppio sull'elemento che batte e la metà su quello che lo batte.",
    label: "Profilo",
    close: "Chiudi",
    tabs: { overview: "Riepilogo", traits: "Tratti", history: "Storia", egg: "Uovo" },
    readyToHatch: "Pronto a schiudersi",
    hatchesIn: "Si schiude tra {time}",
    onTheWayHome: "Sta tornando a casa · {time}",
    onTheWayText: "L'hai richiamato dalla natura: il suo posto è tenuto e atterra a breve.",
    inTheWild: "Nella natura",
    inTheWildText: "Non può gareggiare né partecipare a un rito finché non lo richiami a casa.",
    slumbering: "Dorme · si sveglia tra {time}",
    slumberingText: "Ha donato parte della sua anima all'altare e per ora non può gareggiare né partecipare a un rito.",
    lineage: "Albero genealogico",
    parent: "Genitore {key}",
    goneParent: "Non è più qui",
    parents: "Genitori",
    manyParents: "Ognuno dei {count} ha donato parte della sua anima: ogni parte e ogni colore vengono da uno di loro, la forma da tutti.",
    warmed: "Scaldato",
    warmedValue: "{warms} / {limit}",
    hatchStars: { one: "Nasce con {stars} stella", other: "Nasce con {stars} stelle" },
    warmCaption: "Scaldalo una volta all'ora, fino a {limit} volte: ogni volta si schiude un'ora prima e il drago nasce più forte di ⅛ di stella.",
    element: "Elemento",
    breathesWhenAwake: "Torna a soffiare appena si sveglia.",
    breatheButton: "Soffia {element}",
    breathesAsTeen: "Inizia a soffiare quando diventa giovane.",
    breath: "Soffio",
    body: "Corpo",
    shape: "Forma del corpo",
    blendBoth: "La forma mescola quella di entrambi i genitori.",
    blendAll: "La forma mescola quella di tutti i {count} genitori.",
    colours: "Colori",
    honours: "Trofei e medaglie",
    of: "su {count}",
    historyLine: "{division} · S{season} · G{race}",
    starts: "Gare",
    wins: "Vittorie",
    podiums: "Podi",
    noRaces: "Ancora nessuna gara.",
    sendToWild: "Lascialo nella natura",
    sendCaption: "Non perdi niente: puoi richiamarlo a casa quando vuoi.",
    reallySure: "<b>Sei proprio sicuro?</b> La tua stalla resterà vuota.",
    yesSend: "Sì, lascialo andare",
    keep: "Tienilo",
    flewOff: "{name} è volato via nella natura.",
    stars: "Stelle",
    starsHow: "Tieni alti i suoi bisogni per far crescere la prossima stella",
    starsTop: "Cinque stelle: più forte di così non si può",
    starsInfo: "Le stelle dicono quanto è forte, e ogni drago può arrivare a cinque. Ogni ora che i suoi bisogni restano alti diventa un po' più forte; se lo trascuri si ferma e basta. Non perde mai una stella e le tiene tutte crescendo. Le gare non ne aggiungono.",
    strongAgainst: "Forte contro",
    weakAgainst: "Debole contro",
  },
  detailsScreen: {
    starsValue: "{stars} su {max}",
    statValue: "{now} / {top}",
    care: "Cure",
    fatigue: "Fatica",
    genes: "Geni",
    origin: "Origine",
    generation: "Generazione",
    seed: "Seme",
  },
  raceEntryScreen: {
    pickInfo: "Cavalchi un drago per gara. Correre lo stanca e può farlo infortunare; un drago stanco riposa circa un quarto d'ora prima di poter correre di nuovo.",
    fieldInfo: "Le stelle dicono quanto è forte ogni drago e il Fav è il migliore sulla carta. La forma, il percorso e il volo decidono il resto, quindi le sorprese capitano.",
    seasonOver: "La stagione {number} è finita. Fai partire la prossima dalla pagina della lega.",
    onAir: "La gara {number} è in onda con {name}. Una volta partita, la gara si corre fino al traguardo.",
    yourDragonLower: "il tuo drago",
    backToRace: "Torna alla gara",
    yourDragon: "Il tuo drago",
    noneOfAge: {
      kid: "Al momento nessuno dei tuoi draghi è un cucciolo. Fanne crescere uno per entrare in questa lega.",
      teen: "Al momento nessuno dei tuoi draghi è un giovane. Fanne crescere uno per entrare in questa lega.",
      adult: "Al momento nessuno dei tuoi draghi è un adulto. Fanne crescere uno per entrare in questa lega.",
    },
    field: "I partenti",
    starters: { one: "{count} partente, in ordine di cancello", other: "{count} partenti, in ordine di cancello" },
    fav: "Fav",
    actions: { start: "Via alla gara!", pick: "Scegli il tuo drago", noneReady: "Nessun drago pronto", noneToRide: "Nessun drago da cavalcare" },
    autopilot: "La gara parte col pilota automatico: il tuo fantino guida il drago finché non prendi tu le redini.",
  },
  leagueDetailScreen: {
    standingsInfo:
      "Le divisioni sono Bronzo, Argento e Oro, con rivali più forti a ogni gradino. I piazzamenti danno {points} punti alla scuderia del drago, qualunque dei tuoi corra; dopo {races} gare i primi {up} salgono e gli ultimi {down} scendono. Il campione dell'Oro vince il trofeo della lega.",
    zones: {
      up: "I primi {up} salgono in {upTo}.",
      upDown: "I primi {up} salgono in {upTo}, gli ultimi {down} scendono in {downTo}.",
      champion: "Il campione della divisione {division} è il campione della lega.",
      championDown: "Il campione della divisione {division} è il campione della lega, gli ultimi {down} scendono in {downTo}.",
    },
    seasonComplete: "Stagione {number} conclusa",
    noChampion: "Nessun campione",
    trophyYours: "Il trofeo è tuo! Lo trovi in bacheca, sotto Altro.",
    prizeEgg: { one: "Un uovo in premio ti aspetta nella stalla: nasce con {stars} stella.", other: "Un uovo in premio ti aspetta nella stalla: nasce con {stars} stelle." },
    ceremony: "Premiazione",
    ceremonyShort: "Premiazione",
    nextSeason: "Stagione {number} in {division}",
    nextRace: "Prossima gara",
    raceOf: "Gara {number} di {of}",
    rivals: "Le stesse {count} scuderie rivali della divisione {division} corrono tutte le gare della stagione; tu le sfidi con uno dei tuoi.",
    ready: { one: "{ready} su {count} {age} pronto a correre.", other: "{ready} dei tuoi {count} {ages} pronti a correre." },
    backToRace: "Torna alla gara",
    enterRace: "Iscriviti alla gara",
    standings: "Classifica",
    noRacesYet: "Ancora nessuna gara in questa stagione. Punti per piazzamento: {points}.",
    thisSeason: "Questa stagione",
    racesEmpty: "Qui trovi le gare della stagione, con risultati e repliche.",
    raceTitle: "Gara {number} · {course}",
    yours: "(tuo)",
    yourPlacings: "I tuoi: {placings}",
    results: "Risultati",
    watch: "Guarda",
    watchLabel: "Guarda la gara {number}",
    pastSeasons: "Stagioni passate",
    pastTitle: "Stagione {number} · {division}",
  },
  racesScreen: {
    noneOfAge: "Nessun {age} nella stalla",
    onAir: "In onda",
    newSeason: "Nuova stagione",
    enter: "Iscriviti",
    best: { hold: "Tuo: {place}", promote: "Tuo: {place}, in promozione", relegate: "Tuo: {place}, in retrocessione" },
    noPoints: "Ancora nessun punto",
    season: "Stagione {number} · {next}",
    nextRace: "gara {number} di {of} · {course}",
    complete: "conclusa",
    locked: "Bloccata",
    raceTitle: "{league} · Gara {number}",
    raceDetail: "Stagione {season} · {division} · {course} · {date}",
    results: "Risultati",
    watch: "Guarda",
    watchLabel: "Guarda {league}, gara {number}",
    note: "Ogni drago corre nella lega della sua età: prima i cuccioli, poi i giovani, poi il Gran Premio.",
    recent: "Gare recenti",
    moreOnLeague: "Tutte le gare della stagione sono nella pagina della lega.",
    empty: "Qui compaiono le gare dei tuoi draghi, dalla più recente.",
  },
  resultsScreen: {
    title: "{league} · Gara {number}",
    stamp: "{place}!",
    finish: "TRAGUARDO!",
    dnf: "RIT",
    podium: "Podio",
    photoFinish: "Fotofinish",
    photoMargin: "{name} per {gap} s",
    gap: "+{gap} s",
    order: "Ordine d'arrivo",
    yourDragons: "I tuoi draghi",
    points: { one: "+{count} punto", other: "+{count} punti" },
    gone: "Non è più nella stalla.",
    starts: { one: "{count} gara", other: "{count} gare" },
    wins: { one: "{count} vittoria", other: "{count} vittorie" },
    podiums: { one: "{count} podio", other: "{count} podi" },
    standingsAfter: "Classifica dopo la gara {number} di {of}",
    seasonOver: "La stagione {number} è finita",
    ceremony: "Premiazione",
    watchAgain: "Riguarda",
    backToLeague: "Torna alla lega",
  },
  ceremonyScreen: {
    title: "Premiazione",
    stamps: {
      champions: "Campioni!",
      divisionChamps: "Primi in {division}!",
      promoted: "Promossi!",
      relegated: "Retrocessi",
      place: "{place}!",
      over: "Stagione finita",
    },
    trophy: "Il trofeo {league} è tuo!",
    trophyDetail: "{name} è il campione della lega.",
    medal: "Medaglia del {place} posto",
    medalDetail: "{name}, {place} in {division}.",
    prizeEgg: "Un uovo in premio!",
    prizeDetail: { one: "Un uovo selvatico, niente della tua stalla: nasce con {stars} stella.", other: "Un uovo selvatico, niente della tua stalla: nasce con {stars} stelle." },
    prizeLeft: "{name}, il più anziano, è partito per la natura per fare spazio; puoi richiamarlo a casa.",
    you: "Tu",
    noChampion: "Nessun campione",
    finalStandings: "Classifica finale",
    nextSeason: "Stagione {number} in {division}",
    replay: "Rivedi la premiazione",
    backToLeague: "Torna alla lega",
  },
  leagueLook: {
    leagues: { kids: "Lega Cuccioli", teens: "Lega Giovani", adults: "Gran Premio" },
    divisions: { bronze: "Bronzo", silver: "Argento", gold: "Oro" },
    courses: { canyon: "Canyon", valley: "Valle" },
    ageNouns: {
      kid: { one: "cucciolo", other: "cuccioli" },
      teen: { one: "giovane", other: "giovani" },
      adult: { one: "adulto", other: "adulti" },
    },
    theAges: { kid: "i cuccioli", teen: "i giovani", adult: "gli adulti" },
    placing: "{place} {name}",
    seasonBegins: "{league}: la stagione {number} parte in {division}!",
    locked: {
      tooYoung: "I tuoi draghi sono ancora troppo piccoli: qui corrono solo {theAges}.",
      outgrown: "I tuoi draghi sono ormai troppo grandi: qui corrono solo {theAges}.",
      noKid: "Non hai ancora un cucciolo nella stalla: fai schiudere un uovo per correre qui.",
      none: "Nessun {age} nella stalla: qui corrono solo {theAges}.",
    },
  },
  seasonOutcome: {
    noneRaced: "Nessuno dei tuoi ha corso: resti in {division}.",
    promoted: "La tua scuderia ha chiuso {place}: promozione in {division}!",
    relegated: "La tua scuderia ha chiuso {place}: retrocessione in {division}.",
    stayed: "La tua scuderia ha chiuso {place}: resti in {division}.",
    leagueChampion: "Campione della lega",
    divisionChampion: "Campione della divisione {division}",
  },
  honoursLook: {
    leagueChampion: "Campione della lega",
    trophyDetail: "{league} · {division} · stagione {season}",
    medalTitle: "{place} in {division}",
    medalDetail: "{league} · stagione {season}",
    count: { one: "{count} premio", other: "{count} premi" },
  },
  standingsList: { stable: "Scuderia", wins: "V", points: "Pt" },
  stableView: {
    giftEgg: "Uovo in regalo",
    starts: { one: "{count} gara", other: "{count} gare" },
    wins: { one: "{count} vittoria", other: "{count} vittorie" },
    podiums: { one: "{count} podio", other: "{count} podi" },
    noRaces: "Ancora nessuna gara",
    gameDate: "Giorno {day} · {time}",
  },
  blockText: {
    onAir: "In onda",
    tired: "Stanco",
    slumbering: "Assopito",
    wrongAge: "Età sbagliata",
    stableFull: "La stalla è piena",
    injury: { wing: "Ala stirata", leg: "Zampa dolorante", membrane: "Membrana strappata" },
    ritual: {
      needTwo: "Scegli almeno due draghi",
      notInStable: "{name} non è nella stalla",
      adultsOnly: "Possono partecipare solo gli adulti",
      unfit: "{name}: {reason}",
      slumbering: "{name} è assopito",
    },
    wild: {
      alreadyWild: "È già in libertà",
      notInStable: "Non è nella stalla",
      adultsOnly: "Solo gli adulti possono vivere in libertà",
      notWild: "Non è in libertà",
      onTheWay: "Sta già tornando a casa",
    },
  },
  cloudSave: { icloud: "iCloud", google: "il tuo account Google" },
  altarScreen: {
    skip: "Salta",
    custodian: "Custode",
    emptyPlace: "Posto libero {n}, scegli un adulto",
    leavePlace: "{name}, tocca per farlo uscire dal cerchio",
    growing: "Stanno crescendo: {list}.",
    growingOne: "{name} ({age}, adulto tra {time})",
    eggLabel: "C'è un uovo sull'altare",
    silentLabel: "Le pietre tacciono",
    eggStamp: "Un uovo!",
    silentStamp: "Silenzio",
    eggTitle: "C'è un uovo sull'altare!",
    silentTitle: "Le pietre tacciono...",
    eggText: "È già nella stalla, al sicuro nel suo posto.",
    silentText: "Niente uovo stavolta: le probabilità erano del {odds}.",
    seeEgg: "Vai all'uovo",
    backToAltar: "Torna all'altare",
    needsTwo: "All'altare servono due adulti",
    onlyAdult: "{name} è l'unico adulto nella tua stalla. Per un rituale ne servono almeno due.",
    noAdults: "Nella tua stalla non ci sono adulti. Per un rituale ne servono almeno due.",
    backToStable: "Torna alla stalla",
    chance: "probabilità di un uovo",
    tradeoff: "Con più genitori l'uovo è più probabile ma meno prevedibile: ogni parte e ogni colore arriva intero da uno di loro.",
    begin: "Inizia",
    adults: "Adulti",
    cannotJoin: "Non possono partecipare",
    circleFull: "Il cerchio è pieno. Tocca uno dei draghi nel cerchio per fare spazio.",
    oddsInfo: "Con due genitori la probabilità è del {base}%; ogni genitore in più aggiunge meno del precedente, fino al {top}% con {most}. Uovo o no, poi tutti i genitori dormono, {success} ore dopo un uovo e {failure} se le pietre tacciono.",
    adultsInfo: "Un uovo si schiude con metà della media delle stelle dei genitori. Prende ogni parte, l'elemento e ogni colore intero da un genitore, a volte mutando in qualcosa che nessun genitore mostra, e mescola la forma di tutti.",
  },
  broadcastScreen: {
    catchingUp: "Si torna alla diretta…",
    progress: "Percorso fatto",
    view: "Diretta della gara",
    leave: "Esci dalla gara",
    leaderboard: "Classifica",
    raceControl: "Direzione gara",
    camera: "Telecamera",
    cameraIs: "Telecamera: {camera}",
    cameras: { director: "Regia", rider: "Fantino", free: "Libera", chase: "Inseguimento" },
    pause: "Pausa",
    play: "Riprendi",
    playbackSpeed: "Velocità di riproduzione",
    skip: "Salta al traguardo",
    riding: "In sella",
    autopilot: "Pilota automatico",
    takeReins: "Prendi le redini",
    yourDragon: "Il tuo drago",
    title: "{league} · Gara {race}",
    season: "Stagione {season}",
    exhibition: "Esibizione",
    raceSeed: "Seme gara {seed}",
    sub: "{sub} · {course}",
    finished: "Arrivato",
    loading: { back: "Si torna in gara…", canyon: "Scolpiamo il canyon…", valley: "Disegniamo la valle…" },
    injured: "{name}: {injury} dopo la gara.",
  },
  commentaryLine: {
    grid: { one: "{count} drago si schiera in griglia…", other: "{count} draghi si schierano in griglia…" },
    start: { valley: "E si parte, tutti dentro la valle!", canyon: "E si parte, tutti dentro il canyon!", course: "E si parte, via sul percorso!" },
    wins: "{who} vince!",
    finish: "{who} taglia il traguardo {place}.",
    takesLead: "{who} supera {other} e passa in testa!",
    passes: "{who} supera {other}: ora è {place}.",
    miss: "{who} manca una porta!",
    dnf: "{who} non arriverà al traguardo.",
    land: {
      water: "{who} fa uno splash nell'acqua!",
      mud: "{who} atterra nel fango!",
      sand: "{who} atterra sulla sabbia!",
      dirt: "{who} tocca terra!",
    },
    thermal: "{who} cavalca una termica.",
    hit: { fire: "Il fuoco di {other} prende {who}!", nature: "Le spine di {other} impigliano {who}!", earth: "La sabbia di {other} respinge {who}!", storm: "Il fulmine di {other} scuote {who}!", water: "Il getto d'acqua di {other} inzuppa {who}!" },
    breath: { fire: "{who} sputa fuoco addosso a {other}!", nature: "{who} scaglia spine contro {other}!", earth: "{who} spara sabbia contro {other}!", storm: "{who} scatena un fulmine su {other}!", water: "{who} spara acqua contro {other}!" },
    superEffective: { fire: "Superefficace! Il fuoco di {other} brucia {who}!", nature: "Superefficace! Le radici di {other} spaccano {who}!", earth: "Superefficace! {other} scarica a terra {who}!", storm: "Superefficace! Il fulmine di {other} fulmina {who}!", water: "Superefficace! {other} spegne {who}!" },
    resisted: "{who} regge il soffio di {other}.",
    form: { perfect: "{who} oggi è in gran forma!", off: "{who} oggi non sembra in forma." },
  },
  countdownOverlay: { grid: "Griglia di partenza", go: "Via!" },
  effectLook: { slow: "Rallentato", daze: "Stordito" },
  riderControls: {
    hint: "Trascina e sterza",
    breathe: "Soffia {element}",
  },
  raceReins: {
    finished: "Arrivato",
    gate: "Porta {gate}/{gates}",
  },
  reinsTour: {
    autopilotTitle: "Pilota automatico",
    autopilotText: "La gara parte col Pilota automatico: il tuo fantino guida {name} per te, sceglie la traiettoria e soffia sui rivali giusti. Mettiti comodo e goditi lo spettacolo.",
    skipTitle: "Non fa per te?",
    skipText: "Non serve guardare ogni gara: tocca la bandiera a scacchi quando vuoi e il tuo fantino porta {name} al traguardo per te, dritto ai risultati.",
    reinsTitle: "Prendi le redini",
    reinsText: "Oppure prendi tu il comando e fai volare {name}: tocca Prendi le redini per scegliere la traiettoria e soffiare quando vuoi tu. Puoi tornare al Pilota automatico quando vuoi.",
    reinsKeys: "Oppure premi R sulla tastiera",
    steerTitle: "Sterza",
    steerText: "Trascina dove vuoi sulla gara: di lato giri, in su sali, in giù scendi in picchiata. Lascia andare e il tuo drago torna sulla sua traiettoria.",
    steerKeys: "Frecce o WASD sulla tastiera",
    gaugesTitle: "Velocità e porte",
    gaugesText: "La tua velocità e la prossima porta. Passa tutte le porte in ordine, dal centro per un piccolo scatto: la freccia ti indica la prossima.",
    backTitle: "Torna al Pilota automatico",
    backText: "Tocca Pilota automatico per far volare di nuovo il tuo fantino, e riprendi le redini quando vuoi.",
    backKeys: "Oppure premi R sulla tastiera",
    ride: "In sella!",
    breathTitle: "Soffio",
    breathText: "{breath} colpisce il rivale davanti o di fianco, poi si ricarica. Ogni elemento ne batte un altro: mettiti dietro al rivale contro cui il tuo è forte.",
    breathKeys: "Spazio, F o E per soffiare",
  },
  careNames: {
    needs: { fullness: "Sazio", happiness: "Felice", cleanliness: "Pulito", exercise: "Allenato", affection: "Affetto" },
    actions: { feed: "Nutri", play: "Gioca", clean: "Lava", exercise: "Allena", groom: "Coccola" },
  },
  minigames: {
    done: "Fatto",
    best: "Record {score}",
    record: "Nuovo record! {name} torna al massimo",
    feed: { title: "Lancia lo spuntino", throw: "Trascina per mirare, lascia per lanciare", grass: "Mancato! La mangia dall'erba", lost: "Persa!", last: "Ancora un errore e lo spuntino finisce" },
    clean: { title: "Ora del bagno", sponge: "Strofina via il fango", rinse: "Risciacqua la schiuma", swing: "Ora l'altro lato!" },
    exercise: { title: "Allenamento", ready: "Tocca a tempo!", pushup: "Flessioni! Tocca a tempo", squat: "Squat! Tocca a tempo", jack: "Saltelli d'ali! Tocca a tempo", crunch: "Addominali di coda! Tocca a tempo", flop: "Stremato!" },
    groom: { title: "Grattini", search: "Accarezzalo e trova dove gli prude", warm: "Fuochino… si sta appoggiando", bliss: "Proprio lì! Continua a grattare", found: "Che goduria! Ora gli prude altrove", snort: "Non sul naso!", record: "Nuovo record! {name} ti vuole ancora più bene" },
    volleyball: { title: "Pallavolo", serve: "Arriva la palla!", catch: "Prendi la palla!", throw: "Rilanciala in alto", dropped: "Ti è caduta!", whiffed: "Mancata! Non l'ha presa" },
    fetch: { title: "Riporta", throw: "Trascina in su per mirare, lascia per lanciare", fetch: "Vai a prenderlo!", stick: "Eccolo che torna col bastone", log: "Ma è un tronco intero…", bone: "Di chi è quell'osso?", plop: "Plof. Non vale neanche la corsa" },
    warm: { title: "Al calduccio", rub: "Strofina l'uovo in cerchio", keep: "Perfetto, tienilo così!", hot: "Troppo caldo! Piano", fizzle: "Sfrigola! Più piano stavolta", cosy: "Bello caldo!", record: "Nuovo record di calduccio!" },
  },
  formatDuration: { d: "{count}g", h: "{count}h", m: "{count}m", s: "{count}s" },
  hitFloats: { super: "Superefficace!", resisted: "Resistito", hit: "Colpito!" },
  formLook: {
    perfect: "In gran forma",
    off: "Fuori forma",
    line: { perfect: "Oggi {name} è in gran forma", off: "Oggi {name} è un po' fuori forma" },
    info: {
      perfect: "Forma del giorno: in gran forma, nella prossima gara accelera e vola un filo più veloce.",
      off: "Forma del giorno: un po' fuori forma, nella prossima gara accelera e vola un filo più piano.",
    },
  },
};
