#!/usr/bin/env node

import { spawnSync } from "node:child_process";
import { randomBytes } from "node:crypto";
import {
  existsSync,
  readFileSync,
  writeFileSync,
  rmSync,
  statSync,
  mkdtempSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

import { writeBuild } from "./build.mjs";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");

// Adapted from Belt Nine's deploy. The box is shared: this deploy owns only its own directory,
// systemd unit and nginx vhost.
const SERVER_NAME = "p2.curzel.it";
const APP_DIR = "/opt/sportz";
const SERVICE = "sportz";
const OWNER = "www-data";
// There is no data directory: the box runs a file server and has nothing to keep. Anything that
// ever has to survive a deploy needs a directory outside /opt/sportz.
const APP_PORT = 8094; // the unit's PORT; server/main.mjs reads it from the environment
const NODE_MIN_MAJOR = 18;

// How many release directories the box keeps: the live one and the two it can roll back to.
export const KEEP_RELEASES = 3;

// The payload is the server plus everything it serves; evidence (shots/) and local progress
// (runtime/) stay local. dist/ is the built single-file game page, written by stepStage (the lab
// and race tools still load their modules straight from src/).
const PAYLOAD = [
  "package.json",
  "server",
  "src",
  "styles",
  "dist",
  "index.html",
  "lab.html",
  "race.html",
  "raceMap.html",
  "cameraMap.html",
  "style.css",
];
const REQUIRED = PAYLOAD;
// What has to exist inside a staged release before it is allowed to become the live one.
const REQUIRED_FILES = [
  ...REQUIRED,
  "server/main.mjs",
  "src/app.js",
  "dist/index.html",
  "dist/index.html.br",
];

// WHAT SURVIVES A FAILURE, STAGE BY STAGE. Every payload lands in its own release directory and
// the service reads whichever one `current` points at, so the only mutation that can break a
// running install is the symlink swap - and that one is a rename.
//
//   sanity, packages   nothing of ours has changed yet
//   prepare            directories exist; an install from before this layout is adopted as a release
//   stage, validate    a new release directory exists, unvalidated; `current` still points at the old one
//   activate           `current` -> the new release, atomically; the old release is still on disk
//   service, nginx     the unit and vhost are rewritten; a failure rolls `current` back and restarts
//   certs              best-effort, never fatal: the site is already serving over HTTP
//   health             the last gate; a failure rolls `current` back and restarts
//   prune              only after health passes: old releases beyond KEEP_RELEASES, and the pre-release layout
//
// A first install has no release to go back to. A failure after activation there removes `current`
// and stops the service rather than leaving a half-install answering requests.

/**
 * @typedef {{app: string, releases: string, current: string, next: string,
 *            user: string, group: string}} Layout
 * @typedef {{exec: (cmd: string, opts?: object) => {code: number, stdout: string, stderr: string},
 *            pipe: (cmd: string, localPath: string) => void}} Remote
 */

/**
 * Where a release lives on the box. Everything the deploy touches hangs off `app`.
 * @returns {Layout}
 */
export function layoutFor(app = APP_DIR, user = OWNER, group = OWNER) {
  return {
    app,
    releases: `${app}/releases`,
    current: `${app}/current`,
    next: `${app}/.next`,
    user,
    group,
  };
}

/** A sortable release name: UTC to the second, plus enough randomness for two deploys a second. */
export function newReleaseId(now = new Date()) {
  const stamp = now
    .toISOString()
    .replace(/[-:.]/g, "")
    .slice(0, 18)
    .replace("T", "-");
  return `${stamp}-${randomBytes(3).toString("hex")}`;
}

// HOST=127.0.0.1 is the whole security story: the process is unreachable except through nginx,
// which owns TLS and the public name. The unit reads the app through `current`, so a deploy is a
// symlink swap and a restart - and node resolves the symlink at startup, which is what keeps a
// running process on the release it was started from.
export function unitFile(layout) {
  return `# Auto-generated by tools/deploy.mjs - the Dragons! dragon racing lab.
[Unit]
Description=Dragons! dragon racing lab
After=network.target

[Service]
Type=simple
User=${layout.user}
Group=${layout.group}
WorkingDirectory=${layout.current}
Environment=NODE_ENV=production
Environment=HOST=127.0.0.1
Environment=PORT=${APP_PORT}
Environment=DIST_ROOT=${layout.current}/dist
ExecStart=/usr/bin/env node ${layout.current}/server/main.mjs
Restart=always
RestartSec=2

[Install]
WantedBy=multi-user.target
`;
}

// The proxied location, identical whichever scheme sits in front of it. The Upgrade/Connection
// pair costs nothing when nothing upgrades and is what would let a relay work through the proxy
// without a second nginx change.
const NGINX_LOCATIONS = `    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    location / {
        proxy_pass http://127.0.0.1:${APP_PORT};
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Modules keep their URLs across deploys: no-cache makes a returning browser revalidate
        # instead of running yesterday's code.
        add_header Cache-Control "no-cache";
    }`;

// A deploy must never downgrade a vhost that already has TLS. If the HTTP-only shape is written
// over a working config and certbot is then skipped or fails, the name has no 443 block, and
// nginx answers that by handing the connection to whichever block is first on 443 - serving a
// different site on this box under a certificate for a different name. So once the box holds a
// certificate for this vhost, this file owns the TLS block and the redirect.
function nginxConf({ cert, options, dhparam }) {
  const head = `# Auto-generated by tools/deploy.mjs - reverse proxy for ${SERVER_NAME}.
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}
`;
  if (!cert) {
    return `${head}# No certificate for this name yet: HTTP only, and certbot --nginx adds TLS.
server {
    listen 80;
    listen [::]:80;
    server_name ${SERVER_NAME};

${NGINX_LOCATIONS}
}
`;
  }
  const tls = [
    `    ssl_certificate /etc/letsencrypt/live/${SERVER_NAME}/fullchain.pem;`,
    `    ssl_certificate_key /etc/letsencrypt/live/${SERVER_NAME}/privkey.pem;`,
    options ? "    include /etc/letsencrypt/options-ssl-nginx.conf;" : null,
    dhparam ? "    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;" : null,
  ]
    .filter(Boolean)
    .join("\n");

  // The :80 block keeps the ACME location reachable - a redirect on the challenge path is
  // a renewal that cannot answer.
  return `${head}server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name ${SERVER_NAME};

${tls}

${NGINX_LOCATIONS}
}

server {
    listen 80;
    listen [::]:80;
    server_name ${SERVER_NAME};

    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}
`;
}

let DRY_RUN = false;

function die(msg) {
  console.error(msg);
  process.exit(1);
}

// ---- env / host key --------------------------------------------------------

function loadEnv(path) {
  if (!existsSync(path)) {
    die(
      `missing ${path}\n` +
        "    Deployment credentials live in .env (git-ignored), same keys as ../flyingquake:\n" +
        "    IP_ADDRESS, SSH_USERNAME, SSH_PASSWORD, CERTBOT_EMAIL",
    );
  }
  const env = {};
  for (const raw of readFileSync(path, "utf8").split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith("#")) continue;
    const eq = line.indexOf("=");
    if (eq === -1) continue;
    const key = line.slice(0, eq).trim();
    let val = line.slice(eq + 1).trim();
    if (
      (val.startsWith('"') && val.endsWith('"')) ||
      (val.startsWith("'") && val.endsWith("'"))
    ) {
      val = val.slice(1, -1);
    }
    env[key] = val;
  }
  for (const required of [
    "IP_ADDRESS",
    "SSH_USERNAME",
    "SSH_PASSWORD",
    "CERTBOT_EMAIL",
  ]) {
    if (!env[required]) die(`missing ${required} in ${path}`);
  }
  return env;
}

// Trust on first use, pinned in the repo. `ssh` does the comparing; this only makes sure it looks
// at that file and not the deployer's ~/.ssh/known_hosts.
const KNOWN_HOSTS = join(ROOT, ".deploy_known_hosts");

function sshOptions() {
  return [
    "-o",
    `UserKnownHostsFile=${KNOWN_HOSTS}`,
    "-o",
    "StrictHostKeyChecking=accept-new",
    "-o",
    "ConnectTimeout=15",
    "-o",
    "LogLevel=ERROR",
    // One login per deploy: every later ssh reuses this connection. Repeated password logins
    // in quick succession were intermittently refused, failing deploys halfway.
    "-o",
    "ControlMaster=auto",
    "-o",
    "ControlPath=/tmp/dragonz-deploy-%C",
    "-o",
    "ControlPersist=120",
  ];
}

// Two ways to reach the box, chosen once and reported, because a deploy that silently
// authenticates differently than you think it does is the failure worth naming. sshpass feeds
// SSH_PASSWORD to `ssh`; the askpass fallback exists because sshpass has no Windows build, while
// OpenSSH ships everywhere. Both authenticate with SSH_PASSWORD out of .env - `ssh` reads a
// password only from a terminal or from the helper named by SSH_ASKPASS.
let TRANSPORT = null;
let ASKPASS = null;

function pickTransport() {
  if (!spawnSync("sshpass", ["-V"], { encoding: "utf8" }).error)
    return "sshpass";
  if (spawnSync("ssh", ["-V"], { encoding: "utf8" }).error) {
    die(
      "neither sshpass nor ssh found - one of them has to be on PATH.\n" +
        "    They are LOCAL tools, not dependencies of this repo: package.json stays empty.",
    );
  }
  return "askpass";
}

// A one-line helper that prints the password, read from the environment so it is never in argv
// (world-readable in `ps`) and never on disk.
function makeAskpass() {
  const dir = mkdtempSync(join(tmpdir(), "dragonz-askpass-"));
  const win = process.platform === "win32";
  const file = join(dir, win ? "askpass.cmd" : "askpass.sh");
  writeFileSync(
    file,
    win
      ? "@echo off\r\necho %MINING_SSH_PW%\r\n"
      : "#!/bin/sh\nprintf '%s\\n' \"$MINING_SSH_PW\"\n",
    { mode: 0o700 },
  );
  process.on("exit", () => {
    try {
      rmSync(dir, { recursive: true, force: true });
    } catch {}
  });
  return file;
}

// argv and environment for one remote command, in whichever transport was picked.
function sshArgv(env, tail) {
  const target = `${env.SSH_USERNAME}@${env.IP_ADDRESS}`;
  if (TRANSPORT === "sshpass") {
    return {
      bin: "sshpass",
      args: ["-e", "ssh", ...sshOptions(), target, ...tail],
      env: { ...process.env, SSHPASS: env.SSH_PASSWORD },
    };
  }
  return {
    bin: "ssh",
    args: [
      ...sshOptions(),
      // Password explicitly: a local key that is not authorised on the box would otherwise burn
      // an attempt and look like a brute-force probe to a server counting failures.
      "-o",
      "PreferredAuthentications=password,keyboard-interactive",
      "-o",
      "PubkeyAuthentication=no",
      target,
      ...tail,
    ],
    env: {
      ...process.env,
      MINING_SSH_PW: env.SSH_PASSWORD,
      SSH_ASKPASS: ASKPASS,
      SSH_ASKPASS_REQUIRE: "force",
      // Older ssh consults the helper only when it believes it has no terminal, which it decides
      // by looking for DISPLAY.
      DISPLAY: process.env.DISPLAY || "required",
    },
  };
}

// Run a command on the box. Returns {code, stdout, stderr}; throws on a non-zero exit
// unless `check: false`. Password goes through SSHPASS in the environment, never argv.
function ssh(env, cmd, { check = true, input = null, quiet = false } = {}) {
  if (!quiet)
    console.log(
      `  ssh> ${cmd.length > 120 ? cmd.slice(0, 117) + "…" : cmd.replace(/\n/g, " ")}`,
    );
  if (DRY_RUN) return { code: 0, stdout: "", stderr: "" };

  const { bin, args, env: spawnEnv } = sshArgv(env, ["bash -s"]);
  const r = spawnSync(bin, args, {
    encoding: input ? "buffer" : "utf8",
    input: input ?? cmd,
    maxBuffer: 64 * 1024 * 1024,
    env: spawnEnv,
  });
  if (r.error) throw r.error;

  const stdout = r.stdout ? r.stdout.toString("utf8") : "";
  const stderr = r.stderr ? r.stderr.toString("utf8") : "";
  if (stdout.trim() && !quiet)
    process.stdout.write(stdout.endsWith("\n") ? stdout : stdout + "\n");
  if (stderr.trim()) process.stderr.write(stderr);
  const code = r.status ?? 0;
  if (check && code !== 0)
    throw new Error(`remote command failed (exit ${code}): ${cmd}\n${stderr}`);
  return { code, stdout, stderr };
}

// Feed a local file into a remote command's stdin. Used to stream a tarball into `tar x`.
function sshPipeFile(env, cmd, localPath) {
  console.log(`  ssh> ${cmd.replace(/\n/g, " ").slice(0, 117)}…`);
  if (DRY_RUN) return;

  // The tarball goes in as stdin from Node rather than through a shell pipe. `bash -c` with
  // `set -o pipefail` needed a POSIX shell on the DEPLOYER's machine, which Windows has no
  // reason to have; handing spawnSync a Buffer does the same job with nothing in between.
  const { bin, args, env: spawnEnv } = sshArgv(env, [cmd]);
  const r = spawnSync(bin, args, {
    input: readFileSync(localPath),
    stdio: ["pipe", "inherit", "inherit"],
    maxBuffer: 256 * 1024 * 1024,
    env: spawnEnv,
  });
  if (r.error) throw r.error;
  if ((r.status ?? 0) !== 0)
    throw new Error(`upload failed (exit ${r.status}): ${cmd}`);
}

/**
 * The box, as the deploy sees it: one way to run a command and one way to stream a file into one.
 * Every step below goes through this and nothing else, which is what lets the checks drive the
 * whole sequence against a directory instead of a server.
 * @returns {Remote}
 */
function sshRemote(env) {
  return {
    exec: (cmd, opts) => ssh(env, cmd, opts),
    pipe: (cmd, localPath) => sshPipeFile(env, cmd, localPath),
  };
}

// Write a file on the box without SFTP: a heredoc with an unexpanded delimiter, so the
// content is taken verbatim - nginx configs are full of $variables that must survive.
function writeRemoteFile(remote, remotePath, content) {
  console.log(`  write> ${remotePath} (${Buffer.byteLength(content)} bytes)`);
  const marker = "MINING_EOF_" + Buffer.byteLength(content);
  remote.exec(
    `set -e\ncat > ${remotePath} <<'${marker}'\n${content}\n${marker}\n`,
    {
      quiet: true,
    },
  );
}

// ---- remote scripts --------------------------------------------------------
// Pure text, so a check can run them against a fixture directory with the same shell the box uses.

// GNU mv wants -T and BSD mv wants -h for the same thing: replace the symlink itself rather than
// move the new one inside the directory it points at. Either way it is a rename, so the swap is
// atomic and nothing ever sees a half-written `current`.
function swapLink(target, link, next) {
  return (
    `ln -sfn ${target} ${next}\n` +
    `mv -T ${next} ${link} 2>/dev/null || mv -h ${next} ${link}`
  );
}

export function prepareScript(layout) {
  const install = `install -d -o ${layout.user} -g ${layout.group}`;
  return `
set -e
if [ -e ${layout.current} ] && [ ! -L ${layout.current} ]; then
  echo "[!] ${layout.current} exists and is not a symlink - refusing to touch it"
  exit 1
fi
${install} ${layout.app} ${layout.releases}
if [ ! -e ${layout.current} ] && [ -f ${layout.app}/package.json ]; then
  adopted=$(date -u +%Y%m%d-%H%M%S)-adopted
  ${install} ${layout.releases}/$adopted
  for name in ${PAYLOAD.join(" ")}; do
    if [ -e ${layout.app}/$name ]; then cp -a ${layout.app}/$name ${layout.releases}/$adopted/; fi
  done
  chown -R ${layout.user}:${layout.group} ${layout.releases}/$adopted
  ${swapLink("releases/$adopted", layout.current, layout.next)}
  echo "  adopted the install already here as releases/$adopted"
fi
`;
}

/** The command the tarball is streamed into. It only ever writes inside the new release. */
export function stageScript(layout, id) {
  const dir = `${layout.releases}/${id}`;
  return (
    `set -e; rm -rf ${dir}; install -d -o ${layout.user} -g ${layout.group} ${dir}; ` +
    `tar xzf - -C ${dir}; chown -R ${layout.user}:${layout.group} ${dir}`
  );
}

export function validateScript(layout, id) {
  const dir = `${layout.releases}/${id}`;
  return `
set -e
for name in ${REQUIRED_FILES.join(" ")}; do
  if [ ! -e ${dir}/$name ]; then echo "[!] the staged release has no $name"; exit 1; fi
done
owner=$(ls -ld ${dir} | awk '{print $3}')
if [ "$owner" != "${layout.user}" ]; then
  echo "[!] ${dir} is owned by $owner, not ${layout.user}"
  exit 1
fi
echo "  staged release complete and owned by ${layout.user}"
`;
}

export function activateScript(layout, id) {
  const target = `releases/${id}`;
  return `
set -e
${swapLink(target, layout.current, layout.next)}
if [ "$(readlink ${layout.current})" != "${target}" ]; then
  echo "[!] ${layout.current} did not switch"
  exit 1
fi
echo "  ${layout.current} -> ${target}"
`;
}

export function restoreScript(layout, target) {
  return `
set -e
if [ ! -d ${layout.app}/${target} ]; then
  echo "[!] ${target} is gone - nothing to restore"
  exit 1
fi
${swapLink(target, layout.current, layout.next)}
echo "  ${layout.current} -> ${target}"
`;
}

export function dropCurrentScript(layout) {
  return `set -e\nrm -f ${layout.current} ${layout.next}\n`;
}

/** Only this attempt's staging: the release it uploaded and the temporary link it may have left. */
export function discardScript(layout, id) {
  return `set -e\nrm -rf ${layout.releases}/${id}\nrm -f ${layout.next}\n`;
}

// Bounded retention, applied only once a deploy is healthy: the live release always stays, and
// with it the KEEP_RELEASES-1 newest others - release names sort by their timestamp.
export function pruneScript(layout, keep = KEEP_RELEASES) {
  return `
set -e
active=$(readlink ${layout.current} 2>/dev/null | sed 's#^releases/##')
seen=0
for name in $(ls -1 ${layout.releases} | sort -r); do
  if [ "$name" = "$active" ]; then continue; fi
  seen=$((seen + 1))
  if [ "$seen" -ge ${keep} ]; then rm -rf ${layout.releases}/"$name"; fi
done
echo "  releases on the box: $(ls -1 ${layout.releases} | wc -l | tr -d ' ')"
`;
}

// The layout before releases existed put the payload straight in the app directory, with a .bak
// copy beside it. Once the release it was adopted into is live and healthy, that copy is dead
// weight - and PAYLOAD is exactly what this deploy ever put there.
export function legacyCleanupScript(layout) {
  return `
set -e
gone=""
for name in ${PAYLOAD.join(" ")}; do
  if [ -e ${layout.app}/$name ]; then rm -rf ${layout.app}/$name; gone="$gone $name"; fi
done
rm -rf ${layout.app}.bak
if [ -n "$gone" ]; then echo "  cleared the pre-release layout:$gone"; fi
`;
}

// ---- local -----------------------------------------------------------------

function run(cmd, args, opts = {}) {
  const r = spawnSync(cmd, args, {
    cwd: ROOT,
    stdio: "inherit",
    shell: false,
    ...opts,
  });
  if (r.error) throw r.error;
  return r.status ?? 0;
}

function capture(cmd, args) {
  const r = spawnSync(cmd, args, { cwd: ROOT, encoding: "utf8" });
  return {
    status: r.status ?? 0,
    stdout: r.stdout ?? "",
    stderr: r.stderr ?? "",
  };
}

// Never deploy a tree whose own checks fail.
function stepTest() {
  console.log("[0] npm test && npm run lint");
  if (DRY_RUN) return;
  if (run("npm", ["test"], { stdio: "ignore" }) !== 0)
    die("npm test fails - fix it before deploying");
  if (run("npm", ["run", "lint"], { stdio: "ignore" }) !== 0)
    die("npm run lint fails - fix it before deploying");
  console.log("  all checks passed");
}

function stepGitCommitPush(message) {
  console.log(`[git] commit + push: ${JSON.stringify(message)}`);
  if (DRY_RUN) return;
  if (capture("git", ["status", "--porcelain"]).stdout.trim()) {
    if (run("git", ["add", "-A"]) !== 0) die("git add failed");
    if (run("git", ["commit", "-m", message]) !== 0) die("git commit failed");
  } else {
    console.log("  working tree clean, skipping commit");
  }
  if (run("git", ["push", "-u", "origin", "HEAD"]) !== 0)
    die("git push failed");
}

// ---- remote steps ----------------------------------------------------------

function stepSanity(remote) {
  console.log("[1] sanity");
  remote.exec("set -e\nhostname\nuname -sr\nhead -2 /etc/os-release || true");
}

// nginx, certbot, and a node new enough to run the server. NodeSource only if the
// distro's node is missing or too old - we do not downgrade or fight an existing one.
function stepPackages(remote) {
  console.log("[2] packages: nginx, certbot, node");
  remote.exec(
    "set -e\nexport DEBIAN_FRONTEND=noninteractive\n" +
      "apt-get update -qq\n" +
      "apt-get install -qq -y nginx ca-certificates curl\n" +
      "systemctl enable --now nginx",
  );

  // CERTBOT ONLY IF THE BOX HAS NONE. This is a SHARED box: apt's certbot is years behind
  // the snap most of these machines actually renew with, and installing it alongside gives
  // the box a second renewal timer running an old binary over renewal configs a newer one
  // wrote - which it says outright ("This might not work") and then fails on. Those certs
  // are not all ours to break.
  const certbot = remote
    .exec("certbot --version 2>&1 | head -1 || true", { check: false })
    .stdout.trim();
  if (/^certbot \d/.test(certbot)) {
    console.log(`  ${certbot} already installed`);
  } else {
    console.log("  no certbot -> installing from apt");
    remote.exec(
      "set -e\nexport DEBIAN_FRONTEND=noninteractive\n" +
        "apt-get install -qq -y certbot python3-certbot-nginx",
    );
  }

  const have = remote
    .exec("node -v 2>/dev/null || true", { check: false })
    .stdout.trim();
  const major = /^v(\d+)/.exec(have);
  if (major && Number(major[1]) >= NODE_MIN_MAJOR) {
    console.log(`  node ${have} is new enough`);
    return;
  }
  console.log(
    `  node ${have || "(absent)"} -> installing Node 22 from NodeSource`,
  );
  remote.exec(
    "set -e\nexport DEBIAN_FRONTEND=noninteractive\n" +
      "curl -fsSL https://deb.nodesource.com/setup_22.x | bash -\n" +
      "apt-get install -qq -y nodejs\nnode -v",
  );
}

// Directories, and the one-time adoption of an install that predates them. Idempotent: a box
// already laid out this way comes out of it unchanged.
function stepPrepare(remote, layout) {
  console.log(`[*] release layout under ${layout.app}`);
  remote.exec(prepareScript(layout));
}

/** Which release the box is serving, as a `releases/<id>` path, or "" on a first install. */
function currentTarget(remote, layout) {
  const out = remote
    .exec(`readlink ${layout.current} 2>/dev/null || true`, {
      check: false,
      quiet: true,
    })
    .stdout.trim();
  return /^releases\/[\w.-]+$/.test(out) ? out : "";
}

// One gzipped tarball, streamed into a `tar x` that only ever writes inside the new release
// directory. Nothing the box is serving is touched here.
function stepStage(remote, layout, id, sourceRoot) {
  console.log(`[3] stage the payload -> ${layout.releases}/${id}`);
  const built = writeBuild(sourceRoot, join(sourceRoot, "dist"));
  console.log(`  build> ${built.length} files into dist/`);
  for (const p of REQUIRED) {
    if (!existsSync(join(sourceRoot, p)))
      throw new Error(`payload missing: ${p}`);
  }
  const payload = PAYLOAD.filter((p) => existsSync(join(sourceRoot, p)));
  console.log(`  payload> ${payload.join(" ")}`);

  const tarDir = mkdtempSync(join(tmpdir(), "dragonz-deploy-"));
  const tarPath = join(tarDir, "app.tar.gz");
  try {
    // Relative archive names avoid Windows tar treating an absolute `-f` path as host:path.
    if (
      run(
        "tar",
        ["--no-xattrs", "-czf", "app.tar.gz", "-C", sourceRoot, ...payload],
        { cwd: tarDir },
      ) !== 0
    ) {
      throw new Error("tar of payload failed");
    }
    console.log(
      `  upload> ${(statSync(tarPath).size / 1024).toFixed(0)} KB tarball`,
    );
    remote.pipe(stageScript(layout, id), tarPath);
  } finally {
    rmSync(tarDir, { recursive: true, force: true });
  }
}

function stepValidate(remote, layout, id) {
  console.log("[3b] validate the staged release");
  remote.exec(validateScript(layout, id));
}

function stepActivate(remote, layout, id) {
  console.log("[3c] activate");
  remote.exec(activateScript(layout, id));
}

function stepService(remote, layout) {
  console.log(`[4] systemd unit ${SERVICE}.service`);
  writeRemoteFile(
    remote,
    `/etc/systemd/system/${SERVICE}.service`,
    unitFile(layout),
  );
  remote.exec(
    `set -e\nsystemctl daemon-reload\nsystemctl enable ${SERVICE}\nsystemctl restart ${SERVICE}`,
  );

  // Insist that OUR unit is the process on the port. "Something answers on 8093" is not
  // enough: a leftover service from an older deploy will hold the port, our unit will
  // crash-loop on EADDRINUSE, and a naive curl check would call that a healthy deploy -
  // which is exactly what happened the first time this ran.
  remote.exec(`
set -e
for i in $(seq 1 20); do
  pid=$(systemctl show ${SERVICE} -p MainPID --value)
  if [ "$pid" != "0" ] && systemctl is-active --quiet ${SERVICE}; then
    listener=$(ss -lptnH "sport = :${APP_PORT}" | grep -o 'pid=[0-9]*' | head -1 | cut -d= -f2)
    if [ "$listener" = "$pid" ] && curl -fsS -o /dev/null http://127.0.0.1:${APP_PORT}/; then
      echo "  ${SERVICE} (pid $pid) owns 127.0.0.1:${APP_PORT}"
      exit 0
    fi
    if [ -n "$listener" ] && [ "$listener" != "$pid" ]; then
      echo "[!] port ${APP_PORT} is held by pid $listener, which is NOT ${SERVICE} (pid $pid):"
      ps -o pid,user,args -p "$listener" || true
      echo "    Retire whatever owns it, then deploy again."
      exit 1
    fi
  fi
  sleep 0.5
done
echo "--- journal ---"
journalctl -u ${SERVICE} -n 40 --no-pager || true
exit 1
`);
}

// What TLS material the box already holds for this name. A certificate here decides the
// shape of the vhost written below - see nginxConf.
function remoteTls(remote) {
  const out = remote.exec(
    `
set +e
[ -f /etc/letsencrypt/live/${SERVER_NAME}/fullchain.pem ] && echo cert
[ -f /etc/letsencrypt/options-ssl-nginx.conf ] && echo options
[ -f /etc/letsencrypt/ssl-dhparams.pem ] && echo dhparam
exit 0
`,
    { quiet: true, check: false },
  ).stdout;
  const has = (k) => new RegExp(`^${k}$`, "m").test(out);
  return {
    cert: has("cert"),
    options: has("options"),
    dhparam: has("dhparam"),
  };
}

function stepNginx(remote) {
  console.log("[5] nginx vhost");
  const tls = remoteTls(remote);
  console.log(
    tls.cert
      ? `  certificate present -> https vhost, :80 redirects`
      : `  no certificate yet -> http-only vhost, certbot adds TLS below`,
  );
  remote.exec("install -d -o www-data -g www-data /var/www/html");
  writeRemoteFile(
    remote,
    `/etc/nginx/sites-available/${SERVER_NAME}`,
    nginxConf(tls),
  );
  remote.exec(
    `ln -sf /etc/nginx/sites-available/${SERVER_NAME} /etc/nginx/sites-enabled/${SERVER_NAME}`,
  );
  remote.exec("nginx -t && systemctl reload nginx");
  return tls;
}

// FIRST ISSUANCE ONLY. Once the certificate exists, the vhost above already carries it and
// renewal belongs to the box's own certbot timer - running `certbot --nginx` on every deploy
// only invites it to rewrite a config that is already correct. Best-effort: a certbot
// failure must not undo a deploy that is already serving over HTTP. Idempotent - re-running
// finishes the job once DNS has propagated.
function stepCerts(remote, tls, email) {
  if (tls.cert) {
    console.log(
      "[6] certbot - certificate already in place; renewal is the box's timer",
    );
    return true;
  }
  console.log("[6] certbot --nginx (first issuance, best-effort)");
  const r = remote.exec(
    "certbot --nginx --non-interactive --agree-tos " +
      `--email ${email} --redirect -d ${SERVER_NAME}`,
    { check: false },
  );
  if (r.code === 0) {
    remote.exec("nginx -t && systemctl reload nginx");
    return true;
  }
  console.log(
    `\n[!] certbot did not succeed (exit ${r.code}). The site is live over HTTP;`,
  );
  console.log(
    `    re-run \`npm run deploy\` once DNS for ${SERVER_NAME} has propagated.`,
  );
  return false;
}

// Verify the public hostname reaches this process rather than another vhost.
function stepHealth(remote, httpsReady) {
  console.log("[7] health checks");
  // --resolve, never a Host header: on https a Host header sends no SNI at all, nginx
  // answers from the DEFAULT 443 block, and the check passes while the name serves someone
  // else. Certificate validation stays ON for the same reason - a fallthrough presents a
  // certificate for another name, and that is the failure this exists to catch.
  const resolve = `--resolve ${SERVER_NAME}:80:127.0.0.1 --resolve ${SERVER_NAME}:443:127.0.0.1`;
  const scheme = httpsReady ? "https" : "http";
  remote.exec(`
set -e
curl -fsS -o /tmp/dragonz_origin http://127.0.0.1:${APP_PORT}/
code=$(curl -fsSL ${resolve} -o /tmp/dragonz_edge -w '%{http_code}' ${scheme}://${SERVER_NAME}/)
echo "  ${scheme}://${SERVER_NAME}/ -> $code, $(wc -c </tmp/dragonz_edge) bytes"
[ -s /tmp/dragonz_edge ] || { echo "[!] the page is empty"; exit 1; }
grep -qi '<html' /tmp/dragonz_edge || { echo "[!] that is not an html page"; exit 1; }
if ! cmp -s /tmp/dragonz_origin /tmp/dragonz_edge; then
  echo "[!] ${SERVER_NAME} does NOT serve ${SERVICE}'s page - the vhost for this name is"
  echo "    missing or points elsewhere, and the request landed on another site."
  exit 1
fi
echo "  page:ok (same bytes as 127.0.0.1:${APP_PORT})"
`);
}

// Housekeeping, and never checked: the deploy is already healthy, and a tidy-up that trips is not
// a reason to take a working release away from the box.
function stepPrune(remote, layout) {
  console.log("[8] retention");
  remote.exec(pruneScript(layout), { check: false });
  remote.exec(legacyCleanupScript(layout), { check: false });
}

/**
 * Undo whatever this attempt did to the live install, and say what is left. Never throws: the
 * failure that got us here is the one worth reporting, so a rollback that fails is attached to it
 * rather than replacing it.
 * @returns {{restored: boolean, note: string, error: Error|null}}
 */
function stepRollback(remote, layout, { previous, failed, activated }) {
  const state = { restored: false, note: "", error: null };
  if (!activated) {
    state.restored = !!previous;
    state.note = previous
      ? `nothing was activated - ${layout.current} still points at ${previous}`
      : `nothing was activated - the box still has no release`;
  }
  console.log("[!] recovering");
  try {
    if (activated && previous) {
      remote.exec(restoreScript(layout, previous));
      state.restored = true;
      state.note = `rolled back to ${previous}`;
    } else if (activated) {
      remote.exec(dropCurrentScript(layout));
      state.note =
        `first install: ${layout.current} removed and ${SERVICE} left stopped, ` +
        "so nothing answers as if the deploy had worked";
    }
    remote.exec(discardScript(layout, failed), { check: false });
    if (activated) {
      remote.exec(
        previous
          ? `systemctl restart ${SERVICE} || true\nsystemctl reload nginx || true\n`
          : `systemctl stop ${SERVICE} || true\nsystemctl reload nginx || true\n`,
        { check: false },
      );
    }
  } catch (e) {
    state.error = e;
    state.note =
      `recovery itself failed (${e.message.split("\n")[0]}) - ${layout.app} is as the ` +
      `failure left it: ${activated ? `${layout.current} may still point at releases/${failed}` : "the live release was never switched"}`;
  }
  console.log(`  ${state.note}`);
  return state;
}

/**
 * Every remote stage of a deploy, in order, with the live release protected from all of them.
 * Throws the original failure with `.recovery` attached when anything goes wrong.
 * @param {Remote} remote
 * @param {{layout?: Layout, releaseId?: string, sourceRoot?: string,
 *          skipCerts?: boolean, certbotEmail?: string}} options
 */
export function deploy(remote, options = {}) {
  const layout = options.layout ?? layoutFor();
  const releaseId = options.releaseId ?? newReleaseId();
  const sourceRoot = options.sourceRoot ?? ROOT;

  stepSanity(remote);
  stepPackages(remote);
  stepPrepare(remote, layout);
  const previous = currentTarget(remote, layout);
  console.log(`  live release: ${previous || "(none - first install)"}`);

  let activated = false;
  try {
    stepStage(remote, layout, releaseId, sourceRoot);
    stepValidate(remote, layout, releaseId);
    stepActivate(remote, layout, releaseId);
    activated = true;
    stepService(remote, layout);
    const tls = stepNginx(remote);
    const httpsReady = options.skipCerts
      ? tls.cert
      : stepCerts(remote, tls, options.certbotEmail);
    stepHealth(remote, httpsReady);
    stepPrune(remote, layout);
    return { releaseId, previous, httpsReady };
  } catch (error) {
    console.error(`\n[!] deploy failed: ${error.message}`);
    error.recovery = stepRollback(remote, layout, {
      previous,
      failed: releaseId,
      activated,
    });
    throw error;
  }
}

// ---- main ------------------------------------------------------------------

function parseArgs(argv) {
  const args = { commit: null, skipCerts: false };
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === "--commit") {
      args.commit = argv[++i];
      if (args.commit === undefined) die("--commit requires a message");
    } else if (argv[i] === "--skip-certs") args.skipCerts = true;
    else if (argv[i] === "--dry-run") DRY_RUN = true;
    else if (argv[i] === "--skip-tests") args.skipTests = true;
    else if (argv[i] === "-h" || argv[i] === "--help") {
      console.log(
        'Usage: npm run deploy [-- --commit "note"] [--skip-certs] [--dry-run]',
      );
      process.exit(0);
    } else die(`unknown argument: ${argv[i]}`);
  }
  return args;
}

function main() {
  const args = parseArgs(process.argv.slice(2));
  const env = loadEnv(join(ROOT, ".env"));
  if (!DRY_RUN) {
    TRANSPORT = pickTransport();
    if (TRANSPORT === "askpass") ASKPASS = makeAskpass();
  }

  console.log(
    `deploying Dragons! -> ${SERVER_NAME} (${env.IP_ADDRESS})${DRY_RUN ? "  [dry run]" : ""}`,
  );
  if (TRANSPORT) console.log(`  transport: ${TRANSPORT} (password from .env)`);
  if (!args.skipTests) stepTest();
  if (args.commit) stepGitCommitPush(args.commit);

  let result;
  try {
    result = deploy(sshRemote(env), {
      skipCerts: args.skipCerts,
      certbotEmail: env.CERTBOT_EMAIL,
    });
  } catch {
    process.exit(1);
  }

  console.log(
    `\ndone -> ${result.httpsReady ? "https" : "http"}://${SERVER_NAME}/`,
  );
  console.log(`  release: ${result.releaseId}`);
  console.log(
    `  logs:    ssh ${env.SSH_USERNAME}@${env.IP_ADDRESS} journalctl -u ${SERVICE} -f`,
  );
  console.log(
    `  restart: ssh ${env.SSH_USERNAME}@${env.IP_ADDRESS} systemctl restart ${SERVICE}`,
  );
}

if (process.argv[1] && pathToFileURL(process.argv[1]).href === import.meta.url)
  main();
